-- Deploy only after identity bindings are manually remediated and RLS v2 is deployed.
-- This migration contains no identity re-binding and must not be used to infer identity from email.
BEGIN;

CREATE TABLE public.security_password_reset_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id uuid NOT NULL,
  target_user_id uuid NOT NULL,
  target_type text NOT NULL CHECK (target_type IN ('athlete', 'coach')),
  action text NOT NULL CHECK (action IN ('temporary_password_reset_attempt', 'temporary_password_reset')),
  reason text NOT NULL CHECK (char_length(reason) <= 500),
  success boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX security_password_reset_audit_target_created_at_idx
  ON public.security_password_reset_audit (target_user_id, created_at DESC);

ALTER TABLE public.security_password_reset_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_password_reset_audit FORCE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.security_password_reset_audit FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.security_password_reset_audit_id_seq FROM anon, authenticated;

-- This function is callable only by the server-side service role. It deliberately
-- accepts a user UUID, never a password or token, and revokes all existing sessions.
CREATE OR REPLACE FUNCTION public.revoke_auth_sessions(target_user_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF target_user_id IS NULL THEN
    RAISE EXCEPTION 'target_user_id is required';
  END IF;

  DELETE FROM auth.sessions WHERE user_id = target_user_id;
END;
$$;

REVOKE ALL ON FUNCTION public.revoke_auth_sessions(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.revoke_auth_sessions(uuid) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_auth_sessions(uuid) TO service_role;

-- Password-change-required is based exclusively on the authenticated UUID binding.
CREATE OR REPLACE FUNCTION pilot_security.password_change_required()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND (
      EXISTS (
        SELECT 1 FROM public.coaches c
        WHERE c.user_id = (SELECT auth.uid()) AND c.must_change_password IS TRUE
      )
      OR EXISTS (
        SELECT 1 FROM public.athletes a
        WHERE a.user_id = (SELECT auth.uid()) AND a.must_change_password IS TRUE
      )
    );
$$;

REVOKE ALL ON FUNCTION pilot_security.password_change_required() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION pilot_security.password_change_required() TO authenticated;

-- Password flag changes are server-only. The application clears the flag only after
-- Supabase Auth has accepted the new password in its authenticated server route.
REVOKE UPDATE (must_change_password) ON TABLE public.athletes FROM authenticated;
REVOKE UPDATE (must_change_password) ON TABLE public.coaches FROM authenticated;
DROP POLICY IF EXISTS athletes_update_own_password_flag ON public.athletes;
DROP POLICY IF EXISTS coaches_update_own_password_flag ON public.coaches;

COMMIT;
