-- Commerce Sprint 1: Product Management
-- Adds product catalog tables without payment-provider integration.

-- Some early LAB33 databases were created before public.blocks.id had an
-- explicit primary key/unique constraint. Product references need a unique
-- target, so add the missing constraint only when the current database needs it.
do $$
declare
  block_id_attnum smallint;
begin
  select attnum
    into block_id_attnum
  from pg_attribute
  where attrelid = 'public.blocks'::regclass
    and attname = 'id'
    and not attisdropped;

  if block_id_attnum is null then
    raise exception 'public.blocks.id does not exist; cannot create product block references.';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.blocks'::regclass
      and contype in ('p', 'u')
      and conkey = array[block_id_attnum]::smallint[]
  ) then
    alter table public.blocks
      add constraint blocks_id_key unique (id);
  end if;
end $$;

create table if not exists public.training_products (
  id bigint generated by default as identity primary key,
  author_coach_id bigint not null references public.coaches(id) on delete restrict,
  name text not null,
  description text,
  cover_image_url text,
  price_amount integer not null default 0 check (price_amount >= 0),
  currency text not null default 'TWD' check (char_length(currency) = 3),
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  is_active boolean not null default true,
  published_at timestamp with time zone,
  unpublished_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.training_product_blocks (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.training_products(id) on delete cascade,
  block_id bigint not null references public.blocks(id) on delete restrict,
  sort_order integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint training_product_blocks_product_block_key unique (product_id, block_id)
);

create index if not exists idx_training_products_author_coach_id
  on public.training_products (author_coach_id);

create index if not exists idx_training_products_status
  on public.training_products (status);

create index if not exists idx_training_product_blocks_product_id
  on public.training_product_blocks (product_id);

create index if not exists idx_training_product_blocks_block_id
  on public.training_product_blocks (block_id);

alter table public.training_products enable row level security;
alter table public.training_product_blocks enable row level security;

grant select, insert, update, delete on public.training_products to authenticated;
grant select, insert, update, delete on public.training_product_blocks to authenticated;
grant usage, select on sequence public.training_products_id_seq to authenticated;
grant usage, select on sequence public.training_product_blocks_id_seq to authenticated;

drop policy if exists "Coaches can read allowed training products" on public.training_products;
create policy "Coaches can read allowed training products"
  on public.training_products
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.coaches c
      where c.user_id = (select auth.uid())
        and (c.is_head_coach = true or c.id = training_products.author_coach_id)
    )
  );

drop policy if exists "Coaches can create own training products" on public.training_products;
create policy "Coaches can create own training products"
  on public.training_products
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.coaches c
      where c.user_id = (select auth.uid())
        and c.id = training_products.author_coach_id
    )
  );

drop policy if exists "Coaches can update allowed training products" on public.training_products;
create policy "Coaches can update allowed training products"
  on public.training_products
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.coaches c
      where c.user_id = (select auth.uid())
        and (c.is_head_coach = true or c.id = training_products.author_coach_id)
    )
  )
  with check (
    exists (
      select 1
      from public.coaches c
      where c.user_id = (select auth.uid())
        and (c.is_head_coach = true or c.id = training_products.author_coach_id)
    )
  );

drop policy if exists "Coaches can delete allowed training products" on public.training_products;
create policy "Coaches can delete allowed training products"
  on public.training_products
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.coaches c
      where c.user_id = (select auth.uid())
        and (c.is_head_coach = true or c.id = training_products.author_coach_id)
    )
  );

drop policy if exists "Coaches can read allowed product blocks" on public.training_product_blocks;
create policy "Coaches can read allowed product blocks"
  on public.training_product_blocks
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_blocks.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can create allowed product blocks" on public.training_product_blocks;
create policy "Coaches can create allowed product blocks"
  on public.training_product_blocks
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_blocks.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can update allowed product blocks" on public.training_product_blocks;
create policy "Coaches can update allowed product blocks"
  on public.training_product_blocks
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_blocks.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  )
  with check (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_blocks.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can delete allowed product blocks" on public.training_product_blocks;
create policy "Coaches can delete allowed product blocks"
  on public.training_product_blocks
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_blocks.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );
