-- Commerce Sprint 2.1: Team Delivery Hardening
-- Adds multi-coach Team permissions, transaction-safe roster changes,
-- enrollment lifecycle RPCs, and stronger RLS helpers. Review before production.

create table if not exists public.team_coaches (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete restrict,
  coach_id bigint not null references public.coaches(id) on delete restrict,
  role text not null default 'coach' check (role in ('owner', 'manager', 'coach', 'viewer')),
  can_manage_roster boolean not null default false,
  can_manage_programs boolean not null default false,
  can_view_results boolean not null default true,
  status text not null default 'active' check (status in ('active', 'inactive', 'removed')),
  assigned_by bigint references public.coaches(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  removed_at timestamp with time zone
);

create unique index if not exists idx_team_coaches_one_active_coach
  on public.team_coaches (team_id, coach_id)
  where status = 'active';

create index if not exists idx_team_coaches_team_status on public.team_coaches (team_id, status);
create index if not exists idx_team_coaches_coach_status on public.team_coaches (coach_id, status);
create index if not exists idx_team_coaches_owner_guard on public.team_coaches (team_id, role, status);

grant select, insert, update, delete on public.team_coaches to authenticated;
grant usage, select on sequence public.team_coaches_id_seq to authenticated;
alter table public.team_coaches enable row level security;

insert into public.team_coaches (
  team_id,
  coach_id,
  role,
  can_manage_roster,
  can_manage_programs,
  can_view_results,
  status,
  assigned_by
)
select
  t.id,
  t.created_by,
  'owner',
  true,
  true,
  true,
  'active',
  t.created_by
from public.teams t
where t.created_by is not null
  and not exists (
    select 1
    from public.team_coaches tc
    where tc.team_id = t.id
      and tc.coach_id = t.created_by
      and tc.status = 'active'
  );

create or replace function public.ensure_team_has_active_owner()
returns trigger
language plpgsql
as $$
declare
  remaining_owners integer;
begin
  if tg_op = 'DELETE' then
    if old.status = 'active' and old.role = 'owner' then
      select count(*) into remaining_owners
      from public.team_coaches
      where team_id = old.team_id
        and status = 'active'
        and role = 'owner'
        and id <> old.id;
      if remaining_owners < 1 then
        raise exception '每支 Team 至少需要一名 active owner。';
      end if;
    end if;
    return old;
  end if;

  if old.status = 'active'
     and old.role = 'owner'
     and (new.status <> 'active' or new.role <> 'owner') then
    select count(*) into remaining_owners
    from public.team_coaches
    where team_id = old.team_id
      and status = 'active'
      and role = 'owner'
      and id <> old.id;
    if remaining_owners < 1 then
      raise exception '每支 Team 至少需要一名 active owner。';
    end if;
  end if;

  new.updated_at := now();
  if new.status = 'removed' and old.status <> 'removed' then
    new.removed_at := coalesce(new.removed_at, now());
  end if;
  if new.status <> 'removed' then
    new.removed_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_team_coaches_owner_guard on public.team_coaches;
create trigger trg_team_coaches_owner_guard
before update or delete on public.team_coaches
for each row execute function public.ensure_team_has_active_owner();

create or replace function public.add_team_creator_as_owner()
returns trigger
language plpgsql
as $$
begin
  insert into public.team_coaches (
    team_id,
    coach_id,
    role,
    can_manage_roster,
    can_manage_programs,
    can_view_results,
    status,
    assigned_by
  ) values (
    new.id,
    new.created_by,
    'owner',
    true,
    true,
    true,
    'active',
    new.created_by
  ) on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists trg_add_team_creator_as_owner on public.teams;
create trigger trg_add_team_creator_as_owner
after insert on public.teams
for each row execute function public.add_team_creator_as_owner();

create or replace function public.current_coach_id()
returns bigint
language sql
stable
as $$
  select c.id
  from public.coaches c
  where c.user_id = (select auth.uid())
  limit 1;
$$;

create or replace function public.current_coach_is_head()
returns boolean
language sql
stable
as $$
  select coalesce((
    select c.is_head_coach
    from public.coaches c
    where c.user_id = (select auth.uid())
    limit 1
  ), false);
$$;

create or replace function public.coach_has_team_permission(p_team_id bigint, p_permission text)
returns boolean
language sql
stable
as $$
  select public.current_coach_is_head()
    or exists (
      select 1
      from public.team_coaches tc
      where tc.team_id = p_team_id
        and tc.coach_id = public.current_coach_id()
        and tc.status = 'active'
        and (
          p_permission = 'access'
          or tc.role = 'owner'
          or (p_permission = 'roster' and tc.can_manage_roster)
          or (p_permission = 'programs' and tc.can_manage_programs)
          or (p_permission = 'results' and tc.can_view_results)
          or (p_permission = 'coaches' and tc.role = 'owner')
        )
    );
$$;

create or replace function public.coach_can_manage_team(p_team_id bigint)
returns boolean
language sql
stable
as $$
  select public.coach_has_team_permission(p_team_id, 'roster')
    or public.coach_has_team_permission(p_team_id, 'programs')
    or public.coach_has_team_permission(p_team_id, 'coaches');
$$;

create or replace function public.coach_can_manage_team_roster(p_team_id bigint)
returns boolean language sql stable as $$ select public.coach_has_team_permission(p_team_id, 'roster'); $$;

create or replace function public.coach_can_manage_team_programs(p_team_id bigint)
returns boolean language sql stable as $$ select public.coach_has_team_permission(p_team_id, 'programs'); $$;

create or replace function public.coach_can_view_team_results(p_team_id bigint)
returns boolean language sql stable as $$ select public.coach_has_team_permission(p_team_id, 'results'); $$;

create or replace function public.coach_can_manage_team_coaches(p_team_id bigint)
returns boolean language sql stable as $$ select public.coach_has_team_permission(p_team_id, 'coaches'); $$;

-- Refresh RLS policies to use granular team_coaches permissions.
drop policy if exists "Coaches can read manageable teams" on public.teams;
create policy "Coaches can read manageable teams" on public.teams
  for select to authenticated
  using (public.coach_has_team_permission(id, 'access') or public.athlete_has_active_team_access(id));

drop policy if exists "Coaches can update manageable teams" on public.teams;
create policy "Coaches can update manageable teams" on public.teams
  for update to authenticated
  using (public.coach_can_manage_team_coaches(id))
  with check (public.coach_can_manage_team_coaches(id));

drop policy if exists "Coaches and athletes can read team memberships" on public.team_memberships;
create policy "Coaches and athletes can read team memberships" on public.team_memberships
  for select to authenticated
  using (
    public.coach_has_team_permission(team_id, 'access')
    or exists (select 1 from public.athletes a where a.id = team_memberships.athlete_id and a.user_id = (select auth.uid()))
  );

drop policy if exists "Coaches can manage team memberships" on public.team_memberships;
create policy "Coaches can manage team memberships" on public.team_memberships
  for all to authenticated
  using (public.coach_can_manage_team_roster(team_id))
  with check (public.coach_can_manage_team_roster(team_id));

drop policy if exists "Coaches and athletes can read team enrollments" on public.team_product_enrollments;
create policy "Coaches and athletes can read team enrollments" on public.team_product_enrollments
  for select to authenticated
  using (
    public.coach_has_team_permission(team_id, 'access')
    or (
      status = 'active'
      and start_date <= current_date
      and (end_date is null or end_date >= current_date)
      and public.athlete_has_active_team_access(team_id)
    )
  );

drop policy if exists "Coaches can manage team enrollments" on public.team_product_enrollments;
create policy "Coaches can manage team enrollments" on public.team_product_enrollments
  for all to authenticated
  using (public.coach_can_manage_team_programs(team_id))
  with check (public.coach_can_manage_team_programs(team_id));

drop policy if exists "Coaches and athletes can read team programs" on public.team_program_instances;
create policy "Coaches and athletes can read team programs" on public.team_program_instances
  for select to authenticated
  using (
    public.coach_has_team_permission(team_id, 'access')
    or exists (
      select 1
      from public.team_product_enrollments e
      where e.id = team_program_instances.team_product_enrollment_id
        and e.status = 'active'
        and e.start_date <= current_date
        and (e.end_date is null or e.end_date >= current_date)
        and public.athlete_has_active_team_access(e.team_id)
    )
  );

drop policy if exists "Coaches can manage team programs" on public.team_program_instances;
create policy "Coaches can manage team programs" on public.team_program_instances
  for all to authenticated
  using (public.coach_can_manage_team_programs(team_id))
  with check (public.coach_can_manage_team_programs(team_id));

drop policy if exists "Coaches and athletes can read team sessions" on public.team_program_sessions;
create policy "Coaches and athletes can read team sessions" on public.team_program_sessions
  for select to authenticated
  using (
    exists (
      select 1
      from public.team_program_instances p
      where p.id = team_program_sessions.team_program_instance_id
        and (
          public.coach_has_team_permission(p.team_id, 'access')
          or exists (
            select 1
            from public.team_product_enrollments e
            where e.id = p.team_product_enrollment_id
              and e.status = 'active'
              and e.start_date <= current_date
              and (e.end_date is null or e.end_date >= current_date)
              and public.athlete_has_active_team_access(e.team_id)
          )
        )
    )
  );

drop policy if exists "Coaches can manage team sessions" on public.team_program_sessions;
create policy "Coaches can manage team sessions" on public.team_program_sessions
  for all to authenticated
  using (exists (select 1 from public.team_program_instances p where p.id = team_program_sessions.team_program_instance_id and public.coach_can_manage_team_programs(p.team_id)))
  with check (exists (select 1 from public.team_program_instances p where p.id = team_program_sessions.team_program_instance_id and public.coach_can_manage_team_programs(p.team_id)));

drop policy if exists "Athletes and coaches can read team results" on public.athlete_team_session_results;
create policy "Athletes and coaches can read team results" on public.athlete_team_session_results
  for select to authenticated
  using (
    exists (select 1 from public.athletes a where a.id = athlete_team_session_results.athlete_id and a.user_id = (select auth.uid()))
    or exists (
      select 1
      from public.team_program_sessions s
      join public.team_program_instances p on p.id = s.team_program_instance_id
      where s.id = athlete_team_session_results.team_program_session_id
        and public.coach_can_view_team_results(p.team_id)
    )
  );

drop policy if exists "Coaches can read team coach assignments" on public.team_coaches;
create policy "Coaches can read team coach assignments" on public.team_coaches
  for select to authenticated
  using (public.coach_has_team_permission(team_id, 'access'));

drop policy if exists "Team owners can manage team coach assignments" on public.team_coaches;
create policy "Team owners can manage team coach assignments" on public.team_coaches
  for all to authenticated
  using (public.coach_can_manage_team_coaches(team_id))
  with check (public.coach_can_manage_team_coaches(team_id));

create or replace function public.add_or_reactivate_team_member(
  p_team_id bigint,
  p_athlete_id bigint,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean
)
returns table (membership_id bigint, active_roster_count integer, effective_seat_limit integer)
language plpgsql
as $$
declare
  active_count integer;
  strict_limit integer;
  inactive_membership_id bigint;
  new_membership_id bigint;
begin
  if p_actor_coach_id is null then
    raise exception '缺少操作者。';
  end if;

  perform 1 from public.teams where id = p_team_id and is_active = true for update;
  if not found then
    raise exception '找不到球隊。';
  end if;

  if not (
    coalesce(p_actor_is_head_coach, false)
    or exists (
      select 1 from public.team_coaches tc
      where tc.team_id = p_team_id
        and tc.coach_id = p_actor_coach_id
        and tc.status = 'active'
        and (tc.role = 'owner' or tc.can_manage_roster)
    )
  ) then
    raise exception '你沒有權限管理這支球隊 roster。';
  end if;

  perform 1 from public.athletes where id = p_athlete_id;
  if not found then
    raise exception '找不到這位學員。';
  end if;

  perform 1
  from public.team_product_enrollments e
  where e.team_id = p_team_id
    and e.status = 'active'
    and e.start_date <= current_date
    and (e.end_date is null or e.end_date >= current_date)
  for update;

  select min(e.seat_limit) into strict_limit
  from public.team_product_enrollments e
  where e.team_id = p_team_id
    and e.status = 'active'
    and e.start_date <= current_date
    and (e.end_date is null or e.end_date >= current_date)
    and e.seat_limit is not null;

  if exists (
    select 1 from public.team_memberships tm
    where tm.team_id = p_team_id
      and tm.athlete_id = p_athlete_id
      and tm.status = 'active'
  ) then
    raise exception '這位學員已經是 active team member。';
  end if;

  select count(*) into active_count
  from public.team_memberships tm
  where tm.team_id = p_team_id
    and tm.status = 'active';

  if strict_limit is not null and active_count + 1 > strict_limit then
    raise exception '此球隊目前有效課程的最嚴格席次上限為 % 人，已達上限。', strict_limit;
  end if;

  select tm.id into inactive_membership_id
  from public.team_memberships tm
  where tm.team_id = p_team_id
    and tm.athlete_id = p_athlete_id
    and tm.status = 'inactive'
  order by tm.id desc
  limit 1
  for update;

  if inactive_membership_id is not null then
    update public.team_memberships
    set status = 'active', left_at = null, joined_at = now()
    where id = inactive_membership_id
    returning id into new_membership_id;
  else
    insert into public.team_memberships (team_id, athlete_id, status)
    values (p_team_id, p_athlete_id, 'active')
    returning id into new_membership_id;
  end if;

  return query select new_membership_id, active_count + 1, strict_limit;
end;
$$;

revoke execute on function public.add_or_reactivate_team_member(bigint, bigint, bigint, boolean) from public;
revoke execute on function public.add_or_reactivate_team_member(bigint, bigint, bigint, boolean) from anon;
revoke execute on function public.add_or_reactivate_team_member(bigint, bigint, bigint, boolean) from authenticated;
grant execute on function public.add_or_reactivate_team_member(bigint, bigint, bigint, boolean) to service_role;

create or replace function public.transition_team_enrollment(
  p_enrollment_id bigint,
  p_action text,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean
)
returns table (enrollment_id bigint, program_instance_id bigint, enrollment_status text, program_status text)
language plpgsql
as $$
declare
  enrollment_record public.team_product_enrollments%rowtype;
  program_record public.team_program_instances%rowtype;
  next_enrollment_status text;
  next_program_status text;
begin
  if p_actor_coach_id is null then
    raise exception '缺少操作者。';
  end if;
  if p_action not in ('end', 'cancel') then
    raise exception '不支援的狀態轉換。';
  end if;

  select * into enrollment_record
  from public.team_product_enrollments
  where id = p_enrollment_id
  for update;
  if not found then
    raise exception '找不到 enrollment。';
  end if;

  if not (
    coalesce(p_actor_is_head_coach, false)
    or exists (
      select 1 from public.team_coaches tc
      where tc.team_id = enrollment_record.team_id
        and tc.coach_id = p_actor_coach_id
        and tc.status = 'active'
        and (tc.role = 'owner' or tc.can_manage_programs)
    )
  ) then
    raise exception '你沒有權限管理這支球隊課表。';
  end if;

  if enrollment_record.status in ('ended', 'cancelled') then
    raise exception '此 enrollment 已經結束或取消。';
  end if;

  select * into program_record
  from public.team_program_instances
  where team_product_enrollment_id = p_enrollment_id
  for update;

  next_enrollment_status := case when p_action = 'end' then 'ended' else 'cancelled' end;
  next_program_status := case when p_action = 'end' then 'completed' else 'cancelled' end;

  update public.team_product_enrollments
  set status = next_enrollment_status,
      ended_at = case when p_action = 'end' then now() else ended_at end,
      cancelled_at = case when p_action = 'cancel' then now() else cancelled_at end
  where id = p_enrollment_id;

  if found and program_record.id is not null then
    update public.team_program_instances
    set status = next_program_status,
        updated_at = now()
    where id = program_record.id;

    if p_action = 'cancel' then
      update public.team_program_sessions
      set status = 'cancelled', updated_at = now()
      where team_program_instance_id = program_record.id
        and status <> 'completed';
    end if;
  end if;

  return query select p_enrollment_id, program_record.id, next_enrollment_status, next_program_status;
end;
$$;

revoke execute on function public.transition_team_enrollment(bigint, text, bigint, boolean) from public;
revoke execute on function public.transition_team_enrollment(bigint, text, bigint, boolean) from anon;
revoke execute on function public.transition_team_enrollment(bigint, text, bigint, boolean) from authenticated;
grant execute on function public.transition_team_enrollment(bigint, text, bigint, boolean) to service_role;

-- Replace Sprint 2 assignment RPC with team_coaches permission and row locks.
create or replace function public.assign_product_version_to_team(
  p_team_id bigint,
  p_product_version_id bigint,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean,
  p_start_date date,
  p_end_date date,
  p_seat_limit integer,
  p_timezone text
)
returns table (
  enrollment_id bigint,
  program_instance_id bigint,
  sessions_count integer
)
language plpgsql
as $$
declare
  team_record public.teams%rowtype;
  version_record public.training_product_versions%rowtype;
  product_record public.training_products%rowtype;
  block_count integer;
  active_roster_count integer;
  next_enrollment_id bigint;
  next_program_id bigint;
  clean_timezone text := coalesce(nullif(btrim(p_timezone), ''), 'Asia/Taipei');
begin
  if p_actor_coach_id is null then
    raise exception '缺少操作者。';
  end if;

  select * into team_record from public.teams where id = p_team_id and is_active = true for update;
  if not found then
    raise exception '找不到球隊。';
  end if;

  if not (
    coalesce(p_actor_is_head_coach, false)
    or exists (
      select 1 from public.team_coaches tc
      where tc.team_id = p_team_id
        and tc.coach_id = p_actor_coach_id
        and tc.status = 'active'
        and (tc.role = 'owner' or tc.can_manage_programs)
    )
  ) then
    raise exception '你沒有權限指派商品給這支球隊。';
  end if;

  if p_start_date is null then
    raise exception '請選擇開始日期。';
  end if;

  if p_end_date is not null and p_end_date < p_start_date then
    raise exception '結束日期不可早於開始日期。';
  end if;

  if p_seat_limit is not null and p_seat_limit <= 0 then
    raise exception '席次上限必須大於 0。';
  end if;

  if clean_timezone !~ '^[A-Za-z_]+/[A-Za-z0-9_+\-]+(/[A-Za-z0-9_+\-]+)?$' then
    raise exception 'Timezone 格式不正確。';
  end if;

  select * into version_record from public.training_product_versions where id = p_product_version_id;
  if not found or version_record.status <> 'published' then
    raise exception '只能指派 Published Product Version。';
  end if;

  select * into product_record from public.training_products where id = version_record.product_id;
  if not found or product_record.is_active is not true or product_record.status = 'archived' then
    raise exception '商品目前不可指派。';
  end if;

  if not (coalesce(p_actor_is_head_coach, false) or product_record.author_coach_id = p_actor_coach_id) then
    raise exception '你沒有權限指派這個商品。';
  end if;

  select count(*) into block_count
  from public.training_product_blocks
  where product_version_id = p_product_version_id;

  if block_count <= 0 then
    raise exception 'Published version 至少需要一個 Block。';
  end if;

  perform 1
  from public.team_product_enrollments e
  where e.team_id = p_team_id
  for update;

  if exists (
    select 1
    from public.team_product_enrollments e
    where e.team_id = p_team_id
      and e.product_version_id = p_product_version_id
      and e.status = 'active'
  ) then
    raise exception '這支球隊已經有相同 Product Version 的 active enrollment。';
  end if;

  select count(*) into active_roster_count
  from public.team_memberships
  where team_id = p_team_id and status = 'active';

  if p_seat_limit is not null and active_roster_count > p_seat_limit then
    raise exception '目前 active roster 人數已超過席次上限。';
  end if;

  insert into public.team_product_enrollments (
    team_id,
    product_id,
    product_version_id,
    assigned_by,
    start_date,
    end_date,
    seat_limit,
    status,
    access_mode,
    activated_at
  ) values (
    p_team_id,
    product_record.id,
    version_record.id,
    p_actor_coach_id,
    p_start_date,
    p_end_date,
    p_seat_limit,
    'active',
    'dynamic_roster',
    case when p_start_date <= current_date then now() else null end
  ) returning id into next_enrollment_id;

  insert into public.team_program_instances (
    team_product_enrollment_id,
    team_id,
    product_version_id,
    name,
    start_date,
    end_date,
    timezone,
    status,
    source_snapshot_json
  ) values (
    next_enrollment_id,
    p_team_id,
    version_record.id,
    version_record.snapshot_name,
    p_start_date,
    p_end_date,
    clean_timezone,
    case when p_start_date > current_date then 'scheduled' else 'active' end,
    jsonb_build_object(
      'product_id', product_record.id,
      'product_name', product_record.name,
      'product_version_id', version_record.id,
      'version_number', version_record.version_number,
      'snapshot_name', version_record.snapshot_name,
      'generated_at', now()
    )
  ) returning id into next_program_id;

  insert into public.team_program_sessions (
    team_program_instance_id,
    source_product_block_id,
    source_block_id,
    title,
    scheduled_date,
    week_number,
    day_number,
    sort_order,
    status
  )
  select
    next_program_id,
    tpb.id,
    tpb.block_id,
    coalesce(nullif(b.block_name, ''), nullif(b.block_code, ''), version_record.snapshot_name),
    case
      when tpb.week_number is not null and tpb.day_number is not null then p_start_date + (((tpb.week_number - 1) * 7 + (tpb.day_number - 1))::integer)
      else null
    end,
    tpb.week_number,
    tpb.day_number,
    tpb.sort_order,
    'scheduled'
  from public.training_product_blocks tpb
  join public.blocks b on b.id = tpb.block_id
  where tpb.product_version_id = version_record.id
  order by tpb.sort_order;

  return query select next_enrollment_id, next_program_id, block_count;
end;
$$;

revoke execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) from public;
revoke execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) from anon;
revoke execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) from authenticated;
grant execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) to service_role;
