-- Shared team training: a single assignment is visible to every active member,
-- while each athlete records only their own result rows.
begin;

create table public.shared_training_teams (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 120),
  description text not null default '' check (char_length(description) <= 1000),
  created_by_coach_id bigint not null references public.coaches(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shared_training_memberships (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.shared_training_teams(id) on delete cascade,
  athlete_id bigint not null references public.athletes(id) on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (team_id, athlete_id)
);

create table public.shared_training_assignments (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.shared_training_teams(id) on delete cascade,
  block_id bigint not null references public.blocks(id) on delete restrict,
  title text not null default '' check (char_length(title) <= 160),
  start_date date not null,
  end_date date not null,
  notes text not null default '' check (char_length(notes) <= 2000),
  created_by_coach_id bigint not null references public.coaches(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint team_assignments_valid_dates check (end_date >= start_date)
);

create table public.shared_training_exercise_reports (
  id bigint generated by default as identity primary key,
  team_assignment_id bigint not null references public.shared_training_assignments(id) on delete cascade,
  block_exercise_id bigint not null references public.block_exercises(id) on delete restrict,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  actual_sets text not null default '',
  actual_weight text not null default '',
  updated_at timestamptz not null default now(),
  unique (team_assignment_id, block_exercise_id, athlete_id)
);

create index shared_training_teams_creator_idx on public.shared_training_teams (created_by_coach_id);
create index shared_training_memberships_team_active_idx on public.shared_training_memberships (team_id, is_active);
create index shared_training_memberships_athlete_active_idx on public.shared_training_memberships (athlete_id, is_active);
create index shared_training_assignments_team_dates_idx on public.shared_training_assignments (team_id, start_date, end_date);
create index shared_training_reports_athlete_assignment_idx on public.shared_training_exercise_reports (athlete_id, team_assignment_id);

create or replace function pilot_security.can_manage_team(target_team_id bigint)
returns boolean language sql stable security definer set search_path = '' as $$
  select target_team_id is not null and (
    (select pilot_security.is_head_coach())
    or exists (
      select 1 from public.shared_training_teams t
      where t.id = target_team_id
        and t.created_by_coach_id = (select pilot_security.current_coach_id())
    )
  );
$$;
revoke all on function pilot_security.can_manage_team(bigint) from public;
grant execute on function pilot_security.can_manage_team(bigint) to authenticated;

alter table public.shared_training_teams enable row level security;
alter table public.shared_training_memberships enable row level security;
alter table public.shared_training_assignments enable row level security;
alter table public.shared_training_exercise_reports enable row level security;
revoke all on public.shared_training_teams, public.shared_training_memberships, public.shared_training_assignments, public.shared_training_exercise_reports from anon, authenticated;
grant select on public.shared_training_teams, public.shared_training_memberships, public.shared_training_assignments, public.shared_training_exercise_reports to authenticated;
grant insert, update (actual_sets, actual_weight, updated_at) on public.shared_training_exercise_reports to authenticated;
grant usage, select on sequence public.shared_training_exercise_reports_id_seq to authenticated;

create policy shared_training_teams_read_allowed on public.shared_training_teams for select to authenticated using (
  (select pilot_security.can_manage_team(id))
  or exists (select 1 from public.shared_training_memberships m where m.team_id = shared_training_teams.id and m.is_active and (select pilot_security.owns_athlete(m.athlete_id)))
);
create policy shared_training_memberships_read_allowed on public.shared_training_memberships for select to authenticated using (
  (select pilot_security.can_manage_team(team_id)) or (select pilot_security.owns_athlete(athlete_id))
);
create policy shared_training_assignments_read_allowed on public.shared_training_assignments for select to authenticated using (
  (select pilot_security.can_manage_team(team_id))
  or exists (select 1 from public.shared_training_memberships m where m.team_id = shared_training_assignments.team_id and m.is_active and (select pilot_security.owns_athlete(m.athlete_id)))
);
create policy shared_training_reports_read_allowed on public.shared_training_exercise_reports for select to authenticated using (
  (select pilot_security.owns_athlete(athlete_id))
  or exists (select 1 from public.shared_training_assignments a where a.id = team_assignment_id and (select pilot_security.can_manage_team(a.team_id)))
);
create policy shared_training_reports_insert_own on public.shared_training_exercise_reports for insert to authenticated with check (
  (select pilot_security.owns_athlete(athlete_id))
  and exists (select 1 from public.shared_training_assignments a join public.shared_training_memberships m on m.team_id = a.team_id where a.id = team_assignment_id and m.athlete_id = shared_training_exercise_reports.athlete_id and m.is_active)
);
create policy shared_training_reports_update_own on public.shared_training_exercise_reports for update to authenticated using (
  (select pilot_security.owns_athlete(athlete_id))
) with check (
  (select pilot_security.owns_athlete(athlete_id))
  and exists (select 1 from public.shared_training_assignments a join public.shared_training_memberships m on m.team_id = a.team_id where a.id = team_assignment_id and m.athlete_id = shared_training_exercise_reports.athlete_id and m.is_active)
);

commit;
