begin;

alter table public.shared_training_assignments
  add column week_num integer not null default 1 check (week_num >= 1),
  add column day_num integer not null default 1 check (day_num between 1 and 7),
  add column training_category text not null default '其他',
  add column updated_at timestamptz not null default now();

create table public.shared_training_events (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.shared_training_teams(id) on delete cascade,
  title text not null,
  event_type text not null default '其他',
  start_date date not null,
  end_date date not null,
  notes text not null default '',
  created_by_coach_id bigint not null references public.coaches(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shared_training_events_date_range check (end_date >= start_date)
);
create index shared_training_events_team_dates_idx on public.shared_training_events (team_id, start_date, end_date);
alter table public.shared_training_events enable row level security;
revoke all on public.shared_training_events from anon, authenticated;
grant select on public.shared_training_events to authenticated;
create policy shared_training_events_read_allowed on public.shared_training_events for select to authenticated using (
  (select pilot_security.can_manage_team(team_id))
  or exists (select 1 from public.shared_training_memberships m where m.team_id = shared_training_events.team_id and m.is_active and (select pilot_security.owns_athlete(m.athlete_id)))
);

commit;
