-- Commerce Sprint 2: Team Training Product Delivery
-- Adds team delivery without payment providers. Do not run directly in production
-- until reviewed and backed up.

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  sport_type text,
  created_by bigint not null references public.coaches(id) on delete restrict,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.team_memberships (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete restrict,
  athlete_id bigint not null references public.athletes(id) on delete restrict,
  status text not null default 'active' check (status in ('active', 'inactive', 'removed')),
  joined_at timestamp with time zone not null default now(),
  left_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists idx_team_memberships_one_active_member
  on public.team_memberships (team_id, athlete_id)
  where status = 'active';

create table if not exists public.team_product_enrollments (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete restrict,
  product_id bigint not null references public.training_products(id) on delete restrict,
  product_version_id bigint not null references public.training_product_versions(id) on delete restrict,
  assigned_by bigint not null references public.coaches(id) on delete restrict,
  start_date date not null,
  end_date date,
  seat_limit integer check (seat_limit is null or seat_limit > 0),
  status text not null default 'active' check (status in ('draft', 'active', 'ended', 'cancelled')),
  access_mode text not null default 'dynamic_roster' check (access_mode in ('dynamic_roster')),
  created_at timestamp with time zone not null default now(),
  activated_at timestamp with time zone,
  ended_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  constraint team_product_enrollments_date_check check (end_date is null or end_date >= start_date)
);

create unique index if not exists idx_team_product_enrollments_one_active_version
  on public.team_product_enrollments (team_id, product_version_id)
  where status = 'active';

create table if not exists public.team_program_instances (
  id bigint generated by default as identity primary key,
  team_product_enrollment_id bigint not null references public.team_product_enrollments(id) on delete restrict,
  team_id bigint not null references public.teams(id) on delete restrict,
  product_version_id bigint not null references public.training_product_versions(id) on delete restrict,
  name text not null,
  start_date date not null,
  end_date date,
  timezone text not null default 'Asia/Taipei',
  status text not null default 'active' check (status in ('scheduled', 'active', 'completed', 'cancelled')),
  source_snapshot_json jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint team_program_instances_one_main_program unique (team_product_enrollment_id),
  constraint team_program_instances_date_check check (end_date is null or end_date >= start_date)
);

create table if not exists public.team_program_sessions (
  id bigint generated by default as identity primary key,
  team_program_instance_id bigint not null references public.team_program_instances(id) on delete restrict,
  source_product_block_id bigint not null references public.training_product_blocks(id) on delete restrict,
  source_block_id bigint not null references public.blocks(id) on delete restrict,
  title text not null,
  scheduled_date date,
  week_number integer check (week_number is null or week_number > 0),
  day_number integer check (day_number is null or day_number > 0),
  sort_order integer not null default 0 check (sort_order >= 0),
  status text not null default 'scheduled' check (status in ('scheduled', 'available', 'completed', 'cancelled')),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint team_program_sessions_program_sort_key unique (team_program_instance_id, sort_order)
);

create table if not exists public.athlete_team_session_results (
  id bigint generated by default as identity primary key,
  team_program_session_id bigint not null references public.team_program_sessions(id) on delete restrict,
  athlete_id bigint not null references public.athletes(id) on delete restrict,
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'completed', 'skipped')),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  notes text,
  result_json jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint athlete_team_session_results_session_athlete_key unique (team_program_session_id, athlete_id)
);

create index if not exists idx_teams_created_by on public.teams (created_by);
create index if not exists idx_team_memberships_team_status on public.team_memberships (team_id, status);
create index if not exists idx_team_memberships_athlete_status on public.team_memberships (athlete_id, status);
create index if not exists idx_team_product_enrollments_team_status on public.team_product_enrollments (team_id, status);
create index if not exists idx_team_product_enrollments_version on public.team_product_enrollments (product_version_id);
create index if not exists idx_team_program_instances_team_status on public.team_program_instances (team_id, status);
create index if not exists idx_team_program_instances_enrollment on public.team_program_instances (team_product_enrollment_id);
create index if not exists idx_team_program_sessions_program_order on public.team_program_sessions (team_program_instance_id, sort_order);
create index if not exists idx_athlete_team_session_results_athlete on public.athlete_team_session_results (athlete_id);

alter table public.teams enable row level security;
alter table public.team_memberships enable row level security;
alter table public.team_product_enrollments enable row level security;
alter table public.team_program_instances enable row level security;
alter table public.team_program_sessions enable row level security;
alter table public.athlete_team_session_results enable row level security;

grant select, insert, update, delete on public.teams to authenticated;
grant select, insert, update, delete on public.team_memberships to authenticated;
grant select, insert, update, delete on public.team_product_enrollments to authenticated;
grant select, insert, update, delete on public.team_program_instances to authenticated;
grant select, insert, update, delete on public.team_program_sessions to authenticated;
grant select, insert, update, delete on public.athlete_team_session_results to authenticated;
grant usage, select on sequence public.teams_id_seq to authenticated;
grant usage, select on sequence public.team_memberships_id_seq to authenticated;
grant usage, select on sequence public.team_product_enrollments_id_seq to authenticated;
grant usage, select on sequence public.team_program_instances_id_seq to authenticated;
grant usage, select on sequence public.team_program_sessions_id_seq to authenticated;
grant usage, select on sequence public.athlete_team_session_results_id_seq to authenticated;

create or replace function public.coach_can_manage_team(p_team_id bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.teams t
    join public.coaches c on c.user_id = (select auth.uid())
    where t.id = p_team_id
      and (c.is_head_coach = true or c.id = t.created_by)
  );
$$;

create or replace function public.athlete_has_active_team_access(p_team_id bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.team_memberships tm
    join public.athletes a on a.id = tm.athlete_id
    where tm.team_id = p_team_id
      and tm.status = 'active'
      and a.user_id = (select auth.uid())
  );
$$;

-- Teams
create policy "Coaches can read manageable teams" on public.teams
  for select to authenticated
  using (public.coach_can_manage_team(id) or public.athlete_has_active_team_access(id));

create policy "Coaches can create own teams" on public.teams
  for insert to authenticated
  with check (exists (select 1 from public.coaches c where c.user_id = (select auth.uid()) and c.id = teams.created_by));

create policy "Coaches can update manageable teams" on public.teams
  for update to authenticated
  using (public.coach_can_manage_team(id))
  with check (public.coach_can_manage_team(id));

-- Memberships
create policy "Coaches and athletes can read team memberships" on public.team_memberships
  for select to authenticated
  using (
    public.coach_can_manage_team(team_id)
    or exists (select 1 from public.athletes a where a.id = team_memberships.athlete_id and a.user_id = (select auth.uid()))
  );

create policy "Coaches can manage team memberships" on public.team_memberships
  for all to authenticated
  using (public.coach_can_manage_team(team_id))
  with check (public.coach_can_manage_team(team_id));

-- Enrollments
create policy "Coaches and athletes can read team enrollments" on public.team_product_enrollments
  for select to authenticated
  using (
    public.coach_can_manage_team(team_id)
    or (
      status = 'active'
      and start_date <= current_date
      and (end_date is null or end_date >= current_date)
      and public.athlete_has_active_team_access(team_id)
    )
  );

create policy "Coaches can manage team enrollments" on public.team_product_enrollments
  for all to authenticated
  using (public.coach_can_manage_team(team_id))
  with check (public.coach_can_manage_team(team_id));

-- Programs
create policy "Coaches and athletes can read team programs" on public.team_program_instances
  for select to authenticated
  using (
    public.coach_can_manage_team(team_id)
    or exists (
      select 1
      from public.team_product_enrollments e
      where e.id = team_program_instances.team_product_enrollment_id
        and e.status = 'active'
        and e.start_date <= current_date
        and (e.end_date is null or e.end_date >= current_date)
        and public.athlete_has_active_team_access(e.team_id)
    )
  );

create policy "Coaches can manage team programs" on public.team_program_instances
  for all to authenticated
  using (public.coach_can_manage_team(team_id))
  with check (public.coach_can_manage_team(team_id));

-- Sessions
create policy "Coaches and athletes can read team sessions" on public.team_program_sessions
  for select to authenticated
  using (
    exists (
      select 1
      from public.team_program_instances p
      where p.id = team_program_sessions.team_program_instance_id
        and (
          public.coach_can_manage_team(p.team_id)
          or exists (
            select 1
            from public.team_product_enrollments e
            where e.id = p.team_product_enrollment_id
              and e.status = 'active'
              and e.start_date <= current_date
              and (e.end_date is null or e.end_date >= current_date)
              and public.athlete_has_active_team_access(e.team_id)
          )
        )
    )
  );

create policy "Coaches can manage team sessions" on public.team_program_sessions
  for all to authenticated
  using (exists (select 1 from public.team_program_instances p where p.id = team_program_sessions.team_program_instance_id and public.coach_can_manage_team(p.team_id)))
  with check (exists (select 1 from public.team_program_instances p where p.id = team_program_sessions.team_program_instance_id and public.coach_can_manage_team(p.team_id)));

-- Results
create policy "Athletes and coaches can read team results" on public.athlete_team_session_results
  for select to authenticated
  using (
    exists (select 1 from public.athletes a where a.id = athlete_team_session_results.athlete_id and a.user_id = (select auth.uid()))
    or exists (
      select 1
      from public.team_program_sessions s
      join public.team_program_instances p on p.id = s.team_program_instance_id
      where s.id = athlete_team_session_results.team_program_session_id
        and public.coach_can_manage_team(p.team_id)
    )
  );

create policy "Athletes can create own team results" on public.athlete_team_session_results
  for insert to authenticated
  with check (
    exists (select 1 from public.athletes a where a.id = athlete_team_session_results.athlete_id and a.user_id = (select auth.uid()))
    and exists (
      select 1
      from public.team_program_sessions s
      join public.team_program_instances p on p.id = s.team_program_instance_id
      join public.team_product_enrollments e on e.id = p.team_product_enrollment_id
      join public.team_memberships tm on tm.team_id = e.team_id and tm.athlete_id = athlete_team_session_results.athlete_id
      where s.id = athlete_team_session_results.team_program_session_id
        and tm.status = 'active'
        and e.status = 'active'
        and e.start_date <= current_date
        and (e.end_date is null or e.end_date >= current_date)
    )
  );

create policy "Athletes can update own team results" on public.athlete_team_session_results
  for update to authenticated
  using (exists (select 1 from public.athletes a where a.id = athlete_team_session_results.athlete_id and a.user_id = (select auth.uid())))
  with check (
    exists (select 1 from public.athletes a where a.id = athlete_team_session_results.athlete_id and a.user_id = (select auth.uid()))
    and exists (
      select 1
      from public.team_program_sessions s
      join public.team_program_instances p on p.id = s.team_program_instance_id
      join public.team_product_enrollments e on e.id = p.team_product_enrollment_id
      join public.team_memberships tm on tm.team_id = e.team_id and tm.athlete_id = athlete_team_session_results.athlete_id
      where s.id = athlete_team_session_results.team_program_session_id
        and tm.status = 'active'
        and e.status = 'active'
        and e.start_date <= current_date
        and (e.end_date is null or e.end_date >= current_date)
    )
  );

create or replace function public.assign_product_version_to_team(
  p_team_id bigint,
  p_product_version_id bigint,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean,
  p_start_date date,
  p_end_date date,
  p_seat_limit integer,
  p_timezone text
)
returns table (
  enrollment_id bigint,
  program_instance_id bigint,
  sessions_count integer
)
language plpgsql
as $$
declare
  team_record public.teams%rowtype;
  version_record public.training_product_versions%rowtype;
  product_record public.training_products%rowtype;
  block_count integer;
  active_roster_count integer;
  next_enrollment_id bigint;
  next_program_id bigint;
  clean_timezone text := coalesce(nullif(btrim(p_timezone), ''), 'Asia/Taipei');
begin
  if p_actor_coach_id is null then
    raise exception '缺少操作者。';
  end if;

  select * into team_record from public.teams where id = p_team_id and is_active = true;
  if not found then
    raise exception '找不到球隊。';
  end if;

  if not (coalesce(p_actor_is_head_coach, false) or team_record.created_by = p_actor_coach_id) then
    raise exception '你沒有權限管理這支球隊。';
  end if;

  if p_start_date is null then
    raise exception '請選擇開始日期。';
  end if;

  if p_end_date is not null and p_end_date < p_start_date then
    raise exception '結束日期不可早於開始日期。';
  end if;

  if p_seat_limit is not null and p_seat_limit <= 0 then
    raise exception '席次上限必須大於 0。';
  end if;

  if clean_timezone !~ '^[A-Za-z_]+/[A-Za-z0-9_+\-]+(/[A-Za-z0-9_+\-]+)?$' then
    raise exception 'Timezone 格式不正確。';
  end if;

  select * into version_record from public.training_product_versions where id = p_product_version_id;
  if not found or version_record.status <> 'published' then
    raise exception '只能指派 Published Product Version。';
  end if;

  select * into product_record from public.training_products where id = version_record.product_id;
  if not found or product_record.is_active is not true or product_record.status = 'archived' then
    raise exception '商品目前不可指派。';
  end if;

  if not (coalesce(p_actor_is_head_coach, false) or product_record.author_coach_id = p_actor_coach_id) then
    raise exception '你沒有權限指派這個商品。';
  end if;

  select count(*) into block_count
  from public.training_product_blocks
  where product_version_id = p_product_version_id;

  if block_count <= 0 then
    raise exception 'Published version 至少需要一個 Block。';
  end if;

  if exists (
    select 1
    from public.team_product_enrollments e
    where e.team_id = p_team_id
      and e.product_version_id = p_product_version_id
      and e.status = 'active'
  ) then
    raise exception '這支球隊已經有相同 Product Version 的 active enrollment。';
  end if;

  if p_seat_limit is not null then
    select count(*) into active_roster_count
    from public.team_memberships
    where team_id = p_team_id and status = 'active';

    if active_roster_count > p_seat_limit then
      raise exception '目前 active roster 人數已超過席次上限。';
    end if;
  end if;

  insert into public.team_product_enrollments (
    team_id,
    product_id,
    product_version_id,
    assigned_by,
    start_date,
    end_date,
    seat_limit,
    status,
    access_mode,
    activated_at
  ) values (
    p_team_id,
    product_record.id,
    version_record.id,
    p_actor_coach_id,
    p_start_date,
    p_end_date,
    p_seat_limit,
    'active',
    'dynamic_roster',
    now()
  ) returning id into next_enrollment_id;

  insert into public.team_program_instances (
    team_product_enrollment_id,
    team_id,
    product_version_id,
    name,
    start_date,
    end_date,
    timezone,
    status,
    source_snapshot_json
  ) values (
    next_enrollment_id,
    p_team_id,
    version_record.id,
    version_record.snapshot_name,
    p_start_date,
    p_end_date,
    clean_timezone,
    case when p_start_date > current_date then 'scheduled' else 'active' end,
    jsonb_build_object(
      'product_id', product_record.id,
      'product_name', product_record.name,
      'product_version_id', version_record.id,
      'version_number', version_record.version_number,
      'snapshot_name', version_record.snapshot_name,
      'generated_at', now()
    )
  ) returning id into next_program_id;

  insert into public.team_program_sessions (
    team_program_instance_id,
    source_product_block_id,
    source_block_id,
    title,
    scheduled_date,
    week_number,
    day_number,
    sort_order,
    status
  )
  select
    next_program_id,
    tpb.id,
    tpb.block_id,
    coalesce(nullif(b.block_name, ''), nullif(b.block_code, ''), version_record.snapshot_name),
    case
      when tpb.week_number is not null and tpb.day_number is not null then p_start_date + (((tpb.week_number - 1) * 7 + (tpb.day_number - 1))::integer)
      else null
    end,
    tpb.week_number,
    tpb.day_number,
    tpb.sort_order,
    'scheduled'
  from public.training_product_blocks tpb
  join public.blocks b on b.id = tpb.block_id
  where tpb.product_version_id = version_record.id
  order by tpb.sort_order;

  return query select next_enrollment_id, next_program_id, block_count;
end;
$$;

revoke execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) from public;
revoke execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) from anon;
revoke execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) from authenticated;
grant execute on function public.assign_product_version_to_team(bigint, bigint, bigint, boolean, date, date, integer, text) to service_role;
