-- Pilot RLS v2. REVIEW ONLY. Scope: 12 confirmed live Pilot tables.
BEGIN;
CREATE SCHEMA IF NOT EXISTS pilot_security;
REVOKE ALL ON SCHEMA pilot_security FROM PUBLIC;
GRANT USAGE ON SCHEMA pilot_security TO authenticated;

CREATE OR REPLACE FUNCTION pilot_security.current_coach_id() RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT c.id FROM public.coaches c WHERE (SELECT auth.uid()) IS NOT NULL AND c.user_id = (SELECT auth.uid()) LIMIT 1; $$;
CREATE OR REPLACE FUNCTION pilot_security.current_athlete_id() RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT a.id FROM public.athletes a WHERE (SELECT auth.uid()) IS NOT NULL AND a.user_id = (SELECT auth.uid()) LIMIT 1; $$;
CREATE OR REPLACE FUNCTION pilot_security.is_head_coach() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = (SELECT pilot_security.current_coach_id()) AND c.is_head_coach IS TRUE); $$;
CREATE OR REPLACE FUNCTION pilot_security.is_app_member() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT (SELECT pilot_security.current_coach_id()) IS NOT NULL OR (SELECT pilot_security.current_athlete_id()) IS NOT NULL; $$;
CREATE OR REPLACE FUNCTION pilot_security.can_manage_athlete(target_athlete_id bigint) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT target_athlete_id IS NOT NULL AND ((SELECT pilot_security.is_head_coach()) OR EXISTS (SELECT 1 FROM public.coach_athletes ca WHERE ca.coach_id = (SELECT pilot_security.current_coach_id()) AND ca.athlete_id = target_athlete_id)); $$;
CREATE OR REPLACE FUNCTION pilot_security.owns_athlete(target_athlete_id bigint) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$ SELECT target_athlete_id IS NOT NULL AND target_athlete_id = (SELECT pilot_security.current_athlete_id()); $$;
REVOKE ALL ON FUNCTION pilot_security.current_coach_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_security.current_athlete_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_security.is_head_coach() FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_security.is_app_member() FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_security.can_manage_athlete(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION pilot_security.owns_athlete(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION pilot_security.current_coach_id() TO authenticated;
GRANT EXECUTE ON FUNCTION pilot_security.current_athlete_id() TO authenticated;
GRANT EXECUTE ON FUNCTION pilot_security.is_head_coach() TO authenticated;
GRANT EXECUTE ON FUNCTION pilot_security.is_app_member() TO authenticated;
GRANT EXECUTE ON FUNCTION pilot_security.can_manage_athlete(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION pilot_security.owns_athlete(bigint) TO authenticated;

DROP FUNCTION IF EXISTS public.add_or_reactivate_team_member(bigint,bigint,bigint,boolean);
DROP FUNCTION IF EXISTS public.add_team_creator_as_owner();
DROP FUNCTION IF EXISTS public.archive_product(bigint,bigint,boolean);
DROP FUNCTION IF EXISTS public.assign_product_version_to_team(bigint,bigint,bigint,boolean,date,date,integer,text);
DROP FUNCTION IF EXISTS public.athlete_has_active_team_access(bigint);
DROP FUNCTION IF EXISTS public.delete_block_taxonomy_node(text,bigint,text,bigint,boolean);
DROP FUNCTION IF EXISTS public.publish_product_version(bigint,bigint,bigint,boolean);
DROP FUNCTION IF EXISTS public.replace_product_version_blocks(bigint,jsonb,bigint,boolean);
DROP FUNCTION IF EXISTS public.transition_team_enrollment(bigint,text,bigint,boolean);
DROP FUNCTION IF EXISTS public.unpublish_product(bigint,bigint,boolean);

ALTER TABLE public.athlete_block_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.athlete_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.athlete_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_taxonomy_age_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_taxonomy_sports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.block_taxonomy_training_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaches ENABLE ROW LEVEL SECURITY;
DO $policies$ DECLARE p record; BEGIN FOR p IN SELECT schemaname,tablename,policyname FROM pg_catalog.pg_policies WHERE schemaname='public' AND tablename IN ('athlete_block_exercises','athlete_blocks','athlete_events','athletes','block_exercises','block_sections','block_taxonomy_age_groups','block_taxonomy_sports','block_taxonomy_training_categories','blocks','coach_athletes','coaches') LOOP EXECUTE format('DROP POLICY %I ON %I.%I',p.policyname,p.schemaname,p.tablename); END LOOP; END $policies$;

REVOKE ALL PRIVILEGES ON TABLE public.athlete_block_exercises FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.athlete_blocks FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.athlete_events FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.athletes FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.block_exercises FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.block_sections FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.block_taxonomy_age_groups FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.block_taxonomy_sports FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.block_taxonomy_training_categories FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.blocks FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.coach_athletes FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON TABLE public.coaches FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.athlete_block_exercises_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.athlete_blocks_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.athlete_events_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.athletes_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.block_exercises_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.block_sections_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.block_taxonomy_age_groups_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.block_taxonomy_sports_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.block_taxonomy_training_categories_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.blocks_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.coach_athletes_id_seq FROM anon,authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.coaches_id_seq FROM anon,authenticated;
GRANT SELECT ON TABLE public.athlete_block_exercises TO authenticated;
GRANT SELECT ON TABLE public.athlete_blocks TO authenticated;
GRANT SELECT ON TABLE public.athletes TO authenticated;
GRANT SELECT ON TABLE public.block_exercises TO authenticated;
GRANT SELECT ON TABLE public.block_sections TO authenticated;
GRANT SELECT ON TABLE public.block_taxonomy_age_groups TO authenticated;
GRANT SELECT ON TABLE public.block_taxonomy_sports TO authenticated;
GRANT SELECT ON TABLE public.block_taxonomy_training_categories TO authenticated;
GRANT SELECT ON TABLE public.blocks TO authenticated;
GRANT SELECT ON TABLE public.coach_athletes TO authenticated;
GRANT SELECT ON TABLE public.coaches TO authenticated;
GRANT UPDATE (actual_sets,actual_weight) ON public.athlete_block_exercises TO authenticated;
GRANT SELECT,INSERT ON public.athlete_events TO authenticated;
GRANT UPDATE (must_change_password) ON public.athletes,public.coaches TO authenticated;
GRANT USAGE,SELECT ON SEQUENCE public.athlete_events_id_seq TO authenticated;

CREATE POLICY coaches_select_allowed ON public.coaches FOR SELECT TO authenticated USING ((SELECT auth.uid()) IS NOT NULL AND (user_id=(SELECT auth.uid()) OR (SELECT pilot_security.current_coach_id()) IS NOT NULL));
CREATE POLICY coaches_update_own_password_flag ON public.coaches FOR UPDATE TO authenticated USING (id=(SELECT pilot_security.current_coach_id())) WITH CHECK (id=(SELECT pilot_security.current_coach_id()));
CREATE POLICY athletes_select_allowed ON public.athletes FOR SELECT TO authenticated USING ((SELECT pilot_security.owns_athlete(id)) OR (SELECT pilot_security.can_manage_athlete(id)));
CREATE POLICY athletes_update_own_password_flag ON public.athletes FOR UPDATE TO authenticated USING (id=(SELECT pilot_security.current_athlete_id())) WITH CHECK (id=(SELECT pilot_security.current_athlete_id()));
CREATE POLICY coach_athletes_select_allowed ON public.coach_athletes FOR SELECT TO authenticated USING (coach_id=(SELECT pilot_security.current_coach_id()) OR (SELECT pilot_security.is_head_coach()));
CREATE POLICY blocks_select_app_members ON public.blocks FOR SELECT TO authenticated USING ((SELECT pilot_security.is_app_member()));
CREATE POLICY block_sections_select_app_members ON public.block_sections FOR SELECT TO authenticated USING ((SELECT pilot_security.is_app_member()));
CREATE POLICY block_exercises_select_app_members ON public.block_exercises FOR SELECT TO authenticated USING ((SELECT pilot_security.is_app_member()));
CREATE POLICY taxonomy_sports_select_app_members ON public.block_taxonomy_sports FOR SELECT TO authenticated USING ((SELECT pilot_security.is_app_member()));
CREATE POLICY taxonomy_age_groups_select_app_members ON public.block_taxonomy_age_groups FOR SELECT TO authenticated USING ((SELECT pilot_security.is_app_member()));
CREATE POLICY taxonomy_categories_select_app_members ON public.block_taxonomy_training_categories FOR SELECT TO authenticated USING ((SELECT pilot_security.is_app_member()));
CREATE POLICY athlete_blocks_select_allowed ON public.athlete_blocks FOR SELECT TO authenticated USING ((SELECT pilot_security.owns_athlete(athlete_id)) OR (SELECT pilot_security.can_manage_athlete(athlete_id)));
CREATE POLICY athlete_block_exercises_select_allowed ON public.athlete_block_exercises FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.athlete_blocks ab WHERE ab.id=athlete_block_id AND ((SELECT pilot_security.owns_athlete(ab.athlete_id)) OR (SELECT pilot_security.can_manage_athlete(ab.athlete_id)))));
CREATE POLICY athlete_block_exercises_update_own_report ON public.athlete_block_exercises FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.athlete_blocks ab WHERE ab.id=athlete_block_id AND (SELECT pilot_security.owns_athlete(ab.athlete_id)))) WITH CHECK (EXISTS (SELECT 1 FROM public.athlete_blocks ab WHERE ab.id=athlete_block_id AND (SELECT pilot_security.owns_athlete(ab.athlete_id))));
CREATE POLICY athlete_events_select_allowed ON public.athlete_events FOR SELECT TO authenticated USING ((SELECT pilot_security.owns_athlete(athlete_id)) OR (SELECT pilot_security.can_manage_athlete(athlete_id)));
CREATE POLICY athlete_events_insert_own ON public.athlete_events FOR INSERT TO authenticated WITH CHECK ((SELECT pilot_security.owns_athlete(athlete_id)));
COMMIT;
