begin;

create table public.shared_training_week_markers (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.shared_training_teams(id) on delete cascade,
  created_by_coach_id bigint not null references public.coaches(id) on delete restrict,
  start_date date not null,
  end_date date not null,
  week_num integer not null check (week_num >= 1),
  note text not null default '',
  color_key text not null default 'sky' check (color_key in ('sky', 'emerald', 'amber', 'violet', 'rose', 'slate')),
  created_at timestamptz not null default now(),
  constraint shared_training_week_markers_date_range check (end_date >= start_date)
);
create index shared_training_week_markers_team_dates_idx on public.shared_training_week_markers (team_id, start_date, end_date);
alter table public.shared_training_week_markers enable row level security;
revoke all on public.shared_training_week_markers from anon, authenticated;
grant select on public.shared_training_week_markers to authenticated;
create policy shared_training_week_markers_read_allowed on public.shared_training_week_markers for select to authenticated using (
  (select pilot_security.can_manage_team(team_id))
  or exists (select 1 from public.shared_training_memberships m where m.team_id = shared_training_week_markers.team_id and m.is_active and (select pilot_security.owns_athlete(m.athlete_id)))
);

commit;
