-- Phase 1: block taxonomy normalization
-- Review-only migration. Do not apply to production until confirmed.

create table if not exists public.block_taxonomy_sports (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint block_taxonomy_sports_name_key unique (name)
);

create table if not exists public.block_taxonomy_age_groups (
  id bigint generated by default as identity primary key,
  sport_id bigint not null references public.block_taxonomy_sports(id) on delete restrict,
  name text not null,
  sort_order integer,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint block_taxonomy_age_groups_sport_name_key unique (sport_id, name)
);

create table if not exists public.block_taxonomy_training_categories (
  id bigint generated by default as identity primary key,
  age_group_id bigint not null references public.block_taxonomy_age_groups(id) on delete restrict,
  name text not null,
  sort_order integer,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint block_taxonomy_training_categories_age_group_name_key unique (age_group_id, name)
);

alter table public.blocks
  add column if not exists training_category_id bigint references public.block_taxonomy_training_categories(id) on delete restrict;

create index if not exists idx_block_taxonomy_age_groups_sport_id
  on public.block_taxonomy_age_groups (sport_id);

create index if not exists idx_block_taxonomy_training_categories_age_group_id
  on public.block_taxonomy_training_categories (age_group_id);

create index if not exists idx_blocks_training_category_id
  on public.blocks (training_category_id);
