-- Commerce Sprint 1.1: Product Management Hardening
-- Introduces product versions, transactional block replacement, lifecycle RPCs,
-- and backfills existing Sprint 1 product/block data without deleting products.

alter table public.training_products
  add column if not exists archived_at timestamp with time zone;

create table if not exists public.training_product_versions (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.training_products(id) on delete restrict,
  version_number integer not null check (version_number > 0),
  status text not null default 'draft' check (status in ('draft', 'published', 'retired')),
  snapshot_name text not null,
  snapshot_description text,
  snapshot_price_amount integer not null default 0 check (snapshot_price_amount >= 0),
  snapshot_currency text not null default 'TWD' check (snapshot_currency in ('TWD', 'USD')),
  created_at timestamp with time zone not null default now(),
  published_at timestamp with time zone,
  retired_at timestamp with time zone,
  constraint training_product_versions_product_version_key unique (product_id, version_number)
);

create unique index if not exists idx_training_product_versions_one_published
  on public.training_product_versions (product_id)
  where status = 'published';

create index if not exists idx_training_product_versions_product_id
  on public.training_product_versions (product_id);

create index if not exists idx_training_product_versions_status
  on public.training_product_versions (status);

alter table public.training_product_versions enable row level security;

grant select, insert, update, delete on public.training_product_versions to authenticated;
grant usage, select on sequence public.training_product_versions_id_seq to authenticated;

-- Backfill one version per existing product if Sprint 1 data exists.
insert into public.training_product_versions (
  product_id,
  version_number,
  status,
  snapshot_name,
  snapshot_description,
  snapshot_price_amount,
  snapshot_currency,
  created_at,
  published_at,
  retired_at
)
select
  p.id,
  1,
  case
    when p.status = 'published' then 'published'
    when p.status = 'archived' then 'retired'
    else 'draft'
  end,
  p.name,
  p.description,
  coalesce(p.price_amount, 0),
  case when p.currency in ('TWD', 'USD') then p.currency else 'TWD' end,
  coalesce(p.created_at, now()),
  case when p.status = 'published' then coalesce(p.published_at, now()) else null end,
  case when p.status = 'archived' then coalesce(p.unpublished_at, now()) else null end
from public.training_products p
where not exists (
  select 1
  from public.training_product_versions v
  where v.product_id = p.id
);

-- Upgrade Sprint 1 mapping table from product_id to product_version_id.
alter table public.training_product_blocks
  add column if not exists product_version_id bigint references public.training_product_versions(id) on delete cascade,
  add column if not exists week_number integer check (week_number is null or week_number > 0),
  add column if not exists day_number integer check (day_number is null or day_number > 0);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'training_product_blocks'
      and column_name = 'product_id'
  ) then
    update public.training_product_blocks tpb
    set product_version_id = v.id
    from public.training_product_versions v
    where tpb.product_version_id is null
      and tpb.product_id = v.product_id
      and v.version_number = 1;
  end if;
end $$;

alter table public.training_product_blocks
  alter column product_version_id set not null;

alter table public.training_product_blocks
  drop constraint if exists training_product_blocks_product_block_key;

alter table public.training_product_blocks
  drop constraint if exists training_product_blocks_version_sort_key;

alter table public.training_product_blocks
  drop constraint if exists training_product_blocks_sort_order_check;

alter table public.training_product_blocks
  add constraint training_product_blocks_version_sort_key unique (product_version_id, sort_order),
  add constraint training_product_blocks_sort_order_check check (sort_order >= 0);

create index if not exists idx_training_product_blocks_version_id
  on public.training_product_blocks (product_version_id);

-- Keep legacy product_id column nullable for compatibility with partially-applied Sprint 1 DBs,
-- but all application code from Sprint 1.1 uses product_version_id only.

drop policy if exists "Coaches can read allowed training product versions" on public.training_product_versions;
create policy "Coaches can read allowed training product versions"
  on public.training_product_versions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_versions.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can create allowed training product versions" on public.training_product_versions;
create policy "Coaches can create allowed training product versions"
  on public.training_product_versions
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_versions.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can update allowed draft training product versions" on public.training_product_versions;
create policy "Coaches can update allowed draft training product versions"
  on public.training_product_versions
  for update
  to authenticated
  using (
    status = 'draft'
    and exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_versions.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  )
  with check (
    status = 'draft'
    and exists (
      select 1
      from public.training_products p
      join public.coaches c on c.user_id = (select auth.uid())
      where p.id = training_product_versions.product_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

-- Replace Sprint 1 product-block policies so permissions resolve through product versions.
drop policy if exists "Coaches can read allowed product blocks" on public.training_product_blocks;
create policy "Coaches can read allowed product blocks"
  on public.training_product_blocks
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.training_product_versions v
      join public.training_products p on p.id = v.product_id
      join public.coaches c on c.user_id = (select auth.uid())
      where v.id = training_product_blocks.product_version_id
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can create allowed product blocks" on public.training_product_blocks;
create policy "Coaches can create allowed product blocks"
  on public.training_product_blocks
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.training_product_versions v
      join public.training_products p on p.id = v.product_id
      join public.coaches c on c.user_id = (select auth.uid())
      where v.id = training_product_blocks.product_version_id
        and v.status = 'draft'
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can update allowed product blocks" on public.training_product_blocks;
create policy "Coaches can update allowed product blocks"
  on public.training_product_blocks
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.training_product_versions v
      join public.training_products p on p.id = v.product_id
      join public.coaches c on c.user_id = (select auth.uid())
      where v.id = training_product_blocks.product_version_id
        and v.status = 'draft'
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  )
  with check (
    exists (
      select 1
      from public.training_product_versions v
      join public.training_products p on p.id = v.product_id
      join public.coaches c on c.user_id = (select auth.uid())
      where v.id = training_product_blocks.product_version_id
        and v.status = 'draft'
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

drop policy if exists "Coaches can delete allowed product blocks" on public.training_product_blocks;
create policy "Coaches can delete allowed product blocks"
  on public.training_product_blocks
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.training_product_versions v
      join public.training_products p on p.id = v.product_id
      join public.coaches c on c.user_id = (select auth.uid())
      where v.id = training_product_blocks.product_version_id
        and v.status = 'draft'
        and (c.is_head_coach = true or c.id = p.author_coach_id)
    )
  );

create or replace function public.replace_product_version_blocks(
  p_product_version_id bigint,
  p_blocks jsonb,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean
)
returns void
language plpgsql
as $$
declare
  version_row public.training_product_versions%rowtype;
  product_author_id bigint;
  block_item jsonb;
  next_block_id bigint;
  next_week integer;
  next_day integer;
  next_sort integer;
  seen_sorts integer[] := array[]::integer[];
begin
  select *
    into version_row
  from public.training_product_versions
  where id = p_product_version_id
  for update;

  if version_row.id is null then
    raise exception '找不到商品版本。';
  end if;

  select author_coach_id
    into product_author_id
  from public.training_products
  where id = version_row.product_id
  for update;

  if not (coalesce(p_actor_is_head_coach, false) or product_author_id = p_actor_coach_id) then
    raise exception '你沒有權限修改這個商品版本。';
  end if;

  if version_row.status <> 'draft' then
    raise exception 'Published version is read-only. 請先建立新的 draft version。';
  end if;

  if jsonb_typeof(coalesce(p_blocks, '[]'::jsonb)) <> 'array' then
    raise exception 'Blocks payload 格式不正確。';
  end if;

  delete from public.training_product_blocks
  where product_version_id = p_product_version_id;

  for block_item in select * from jsonb_array_elements(coalesce(p_blocks, '[]'::jsonb)) loop
    next_block_id := nullif(block_item->>'block_id', '')::bigint;
    next_week := nullif(block_item->>'week_number', '')::integer;
    next_day := nullif(block_item->>'day_number', '')::integer;
    next_sort := nullif(block_item->>'sort_order', '')::integer;

    if next_block_id is null or next_sort is null then
      raise exception 'Block payload 缺少 block_id 或 sort_order。';
    end if;

    if next_sort < 0 then
      raise exception 'sort_order 必須大於或等於 0。';
    end if;

    if next_week is not null and next_week <= 0 then
      raise exception 'week_number 必須為正整數。';
    end if;

    if next_day is not null and next_day <= 0 then
      raise exception 'day_number 必須為正整數。';
    end if;

    if next_sort = any(seen_sorts) then
      raise exception 'sort_order 不可重複。';
    end if;
    seen_sorts := array_append(seen_sorts, next_sort);

    if not exists (select 1 from public.blocks where id = next_block_id) then
      raise exception '商品包含不存在的板塊。';
    end if;

    insert into public.training_product_blocks (
      product_version_id,
      block_id,
      week_number,
      day_number,
      sort_order
    ) values (
      p_product_version_id,
      next_block_id,
      next_week,
      next_day,
      next_sort
    );
  end loop;
end;
$$;

create or replace function public.publish_product_version(
  p_product_id bigint,
  p_product_version_id bigint,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean
)
returns void
language plpgsql
as $$
declare
  version_row public.training_product_versions%rowtype;
  product_row public.training_products%rowtype;
  block_count integer;
  published_time timestamp with time zone := now();
begin
  select * into product_row
  from public.training_products
  where id = p_product_id
  for update;

  if product_row.id is null then
    raise exception '找不到商品。';
  end if;

  if not (coalesce(p_actor_is_head_coach, false) or product_row.author_coach_id = p_actor_coach_id) then
    raise exception '你沒有權限發布這個商品。';
  end if;

  select * into version_row
  from public.training_product_versions
  where id = p_product_version_id
    and product_id = p_product_id
  for update;

  if version_row.id is null then
    raise exception '找不到商品版本。';
  end if;

  if version_row.status <> 'draft' then
    raise exception '只能發布 draft version。';
  end if;

  if btrim(version_row.snapshot_name) = '' then
    raise exception '商品名稱不可為空。';
  end if;

  if version_row.snapshot_price_amount < 0 then
    raise exception '商品價格不可小於 0。';
  end if;

  if version_row.snapshot_currency not in ('TWD', 'USD') then
    raise exception '商品幣別不支援。';
  end if;

  select count(*) into block_count
  from public.training_product_blocks
  where product_version_id = p_product_version_id;

  if block_count < 1 then
    raise exception '商品至少需要包含一個 Block 才能發布。';
  end if;

  update public.training_product_versions
  set status = 'retired', retired_at = published_time
  where product_id = p_product_id
    and status = 'published'
    and id <> p_product_version_id;

  update public.training_product_versions
  set status = 'published', published_at = published_time, retired_at = null
  where id = p_product_version_id;

  update public.training_products
  set name = version_row.snapshot_name,
      description = version_row.snapshot_description,
      price_amount = version_row.snapshot_price_amount,
      currency = version_row.snapshot_currency,
      status = 'published',
      is_active = true,
      published_at = published_time,
      unpublished_at = null,
      archived_at = null,
      updated_at = published_time
  where id = p_product_id;
end;
$$;

create or replace function public.unpublish_product(
  p_product_id bigint,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean
)
returns void
language plpgsql
as $$
declare
  product_row public.training_products%rowtype;
  unpublished_time timestamp with time zone := now();
begin
  select * into product_row
  from public.training_products
  where id = p_product_id
  for update;

  if product_row.id is null then
    raise exception '找不到商品。';
  end if;

  if not (coalesce(p_actor_is_head_coach, false) or product_row.author_coach_id = p_actor_coach_id) then
    raise exception '你沒有權限下架這個商品。';
  end if;

  update public.training_products
  set status = 'draft',
      is_active = false,
      unpublished_at = unpublished_time,
      updated_at = unpublished_time
  where id = p_product_id;
end;
$$;

create or replace function public.archive_product(
  p_product_id bigint,
  p_actor_coach_id bigint,
  p_actor_is_head_coach boolean
)
returns void
language plpgsql
as $$
declare
  product_row public.training_products%rowtype;
  archived_time timestamp with time zone := now();
begin
  select * into product_row
  from public.training_products
  where id = p_product_id
  for update;

  if product_row.id is null then
    raise exception '找不到商品。';
  end if;

  if not (coalesce(p_actor_is_head_coach, false) or product_row.author_coach_id = p_actor_coach_id) then
    raise exception '你沒有權限封存這個商品。';
  end if;

  update public.training_product_versions
  set status = 'retired', retired_at = coalesce(retired_at, archived_time)
  where product_id = p_product_id
    and status = 'draft';

  update public.training_products
  set status = 'archived',
      is_active = false,
      unpublished_at = archived_time,
      archived_at = archived_time,
      updated_at = archived_time
  where id = p_product_id;
end;
$$;

revoke execute on function public.replace_product_version_blocks(bigint, jsonb, bigint, boolean) from public, anon, authenticated;
revoke execute on function public.publish_product_version(bigint, bigint, bigint, boolean) from public, anon, authenticated;
revoke execute on function public.unpublish_product(bigint, bigint, boolean) from public, anon, authenticated;
revoke execute on function public.archive_product(bigint, bigint, boolean) from public, anon, authenticated;

grant execute on function public.replace_product_version_blocks(bigint, jsonb, bigint, boolean) to service_role;
grant execute on function public.publish_product_version(bigint, bigint, bigint, boolean) to service_role;
grant execute on function public.unpublish_product(bigint, bigint, boolean) to service_role;
grant execute on function public.archive_product(bigint, bigint, boolean) to service_role;
