create table if not exists public.qa_library (
  id bigint generated by default as identity primary key,
  question text not null check (char_length(trim(question)) > 0),
  answer_video_url text not null check (char_length(trim(answer_video_url)) > 0),
  created_by_coach_id bigint references public.coaches(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_qa_library_created_at on public.qa_library(created_at desc);

alter table public.qa_library enable row level security;
revoke all on table public.qa_library from anon, authenticated;
grant select on table public.qa_library to authenticated;
create policy qa_library_select_app_members on public.qa_library for select to authenticated using ((select pilot_security.is_app_member()));
