create table if not exists public.athlete_week_markers (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  created_by_coach_id bigint references public.coaches(id) on delete set null,
  start_date date not null,
  end_date date not null,
  week_num integer not null check (week_num >= 1),
  note text not null default '',
  color_key text not null default 'sky' check (color_key in ('sky', 'emerald', 'amber', 'violet', 'rose', 'slate')),
  created_at timestamptz not null default now(),
  constraint athlete_week_markers_valid_date_range check (end_date >= start_date)
);

create index if not exists athlete_week_markers_athlete_dates_idx
  on public.athlete_week_markers (athlete_id, start_date, end_date);

alter table public.athlete_week_markers enable row level security;
revoke all on table public.athlete_week_markers from anon, authenticated;
revoke all on sequence public.athlete_week_markers_id_seq from anon, authenticated;
grant select on table public.athlete_week_markers to authenticated;

drop policy if exists athlete_week_markers_select_allowed on public.athlete_week_markers;
create policy athlete_week_markers_select_allowed
  on public.athlete_week_markers
  for select
  to authenticated
  using (
    (select pilot_security.owns_athlete(athlete_id))
    or (select pilot_security.can_manage_athlete(athlete_id))
  );
