create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  role text check (role in ('coach', 'athlete')),
  created_at timestamp with time zone default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'role', 'athlete')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    name = excluded.name,
    role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.athletes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  name text,
  email text,
  sport text,
  level text,
  coach_id uuid references public.users(id) on delete set null,
  created_at timestamp with time zone default now()
);

alter table public.athletes add column if not exists name text;
alter table public.athletes add column if not exists email text;

create table if not exists public.periods (
  id bigint generated by default as identity primary key,
  period_name text,
  sport text,
  goal text,
  duration_weeks integer,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.period_blocks (
  id bigint generated by default as identity primary key,
  period_id bigint references public.periods(id) on delete cascade,
  week_num integer,
  day_num integer,
  block_id bigint,
  order_num integer,
  created_at timestamp with time zone default now()
);

create table if not exists public.athlete_programs (
  id bigint generated by default as identity primary key,
  athlete_id bigint references public.athletes(id) on delete cascade,
  period_id bigint references public.periods(id) on delete set null,
  start_date date,
  status text check (status in ('active', 'completed', 'archived')),
  created_at timestamp with time zone default now()
);

create table if not exists public.athlete_program_blocks (
  id bigint generated by default as identity primary key,
  program_id bigint references public.athlete_programs(id) on delete cascade,
  week_num integer,
  day_num integer,
  block_id bigint,
  order_num integer,
  notes text,
  created_at timestamp with time zone default now()
);

alter table public.users enable row level security;
alter table public.athletes enable row level security;
alter table public.periods enable row level security;
alter table public.period_blocks enable row level security;
alter table public.athlete_programs enable row level security;
alter table public.athlete_program_blocks enable row level security;

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
on public.users
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can create own profile" on public.users;
create policy "Users can create own profile"
on public.users
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Coaches can read athletes" on public.athletes;
create policy "Coaches can read athletes"
on public.athletes
for select
to authenticated
using (
  coach_id = auth.uid()
  or user_id = auth.uid()
  or exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
);

drop policy if exists "Coaches can manage athletes" on public.athletes;
create policy "Coaches can manage athletes"
on public.athletes
for all
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
);

drop policy if exists "Authenticated can read periods" on public.periods;
create policy "Authenticated can read periods"
on public.periods
for select
to authenticated
using (true);

drop policy if exists "Coaches can manage periods" on public.periods;
create policy "Coaches can manage periods"
on public.periods
for all
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
);

drop policy if exists "Authenticated can read period blocks" on public.period_blocks;
create policy "Authenticated can read period blocks"
on public.period_blocks
for select
to authenticated
using (true);

drop policy if exists "Coaches can manage period blocks" on public.period_blocks;
create policy "Coaches can manage period blocks"
on public.period_blocks
for all
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
);

drop policy if exists "Users can read own athlete programs" on public.athlete_programs;
create policy "Users can read own athlete programs"
on public.athlete_programs
for select
to authenticated
using (
  exists (
    select 1
    from public.athletes
    where athletes.id = athlete_programs.athlete_id
      and (
        athletes.user_id = auth.uid()
        or athletes.coach_id = auth.uid()
        or exists (
          select 1
          from public.users
          where users.id = auth.uid()
            and users.role = 'coach'
        )
      )
  )
);

drop policy if exists "Coaches can manage athlete programs" on public.athlete_programs;
create policy "Coaches can manage athlete programs"
on public.athlete_programs
for all
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
    and users.role = 'coach'
  )
);

drop policy if exists "Users can read own athlete program blocks" on public.athlete_program_blocks;
create policy "Users can read own athlete program blocks"
on public.athlete_program_blocks
for select
to authenticated
using (
  exists (
    select 1
    from public.athlete_programs
    join public.athletes on athletes.id = athlete_programs.athlete_id
    where athlete_programs.id = athlete_program_blocks.program_id
      and (
        athletes.user_id = auth.uid()
        or athletes.coach_id = auth.uid()
        or exists (
          select 1
          from public.users
          where users.id = auth.uid()
            and users.role = 'coach'
        )
      )
  )
);

drop policy if exists "Coaches can manage athlete program blocks" on public.athlete_program_blocks;
create policy "Coaches can manage athlete program blocks"
on public.athlete_program_blocks
for all
to authenticated
using (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
)
with check (
  exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'coach'
  )
);

drop policy if exists "Development anon access athletes" on public.athletes;
create policy "Development anon access athletes"
on public.athletes
for all
to anon
using (true)
with check (true);

drop policy if exists "Development anon access periods" on public.periods;
create policy "Development anon access periods"
on public.periods
for all
to anon
using (true)
with check (true);

drop policy if exists "Development anon access period blocks" on public.period_blocks;
create policy "Development anon access period blocks"
on public.period_blocks
for all
to anon
using (true)
with check (true);

drop policy if exists "Development anon access athlete programs" on public.athlete_programs;
create policy "Development anon access athlete programs"
on public.athlete_programs
for all
to anon
using (true)
with check (true);

drop policy if exists "Development anon access athlete program blocks" on public.athlete_program_blocks;
create policy "Development anon access athlete program blocks"
on public.athlete_program_blocks
for all
to anon
using (true)
with check (true);

grant usage on schema public to anon;
grant select, insert, update, delete on table public.athletes to anon;
grant select, insert, update, delete on table public.periods to anon;
grant select, insert, update, delete on table public.period_blocks to anon;
grant select, insert, update, delete on table public.athlete_programs to anon;
grant select, insert, update, delete on table public.athlete_program_blocks to anon;
grant usage, select on all sequences in schema public to anon;


create table if not exists public.athlete_events (
  id bigint generated by default as identity primary key,
  athlete_id bigint references public.athletes(id) on delete cascade,
  title text,
  event_type text,
  start_date date,
  end_date date,
  notes text,
  created_at timestamp with time zone default now()
);
