'use client'

import { useMemo, useState } from 'react'
import type { StudentTeamAssignment } from '@/services/team-training'

type Props = { initialAssignments: StudentTeamAssignment[] }
const weekdays = ['一', '二', '三', '四', '五', '六', '日']
function today() { return new Date().toISOString().slice(0, 10) }
function monthLabel(value: string) { const [year, month] = value.split('-'); return `${year} 年 ${Number(month)} 月` }
function shiftMonth(value: string, amount: number) { const [year, month] = value.split('-').map(Number); const date = new Date(year, month - 1 + amount, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}` }
function buildDays(month: string) { const start = new Date(`${month}-01T00:00:00`); const first = (start.getDay() + 6) % 7; const count = new Date(start.getFullYear(), start.getMonth() + 1, 0).getDate(); return Array.from({ length: Math.ceil((first + count) / 7) * 7 }, (_, index) => { const date = new Date(start.getFullYear(), start.getMonth(), index - first + 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` }) }

export function StudentTeamTraining({ initialAssignments }: Props) {
  const [assignments, setAssignments] = useState(initialAssignments)
  const [selectedDate, setSelectedDate] = useState(today())
  const [visibleMonth, setVisibleMonth] = useState(today().slice(0, 7))
  const [savingId, setSavingId] = useState<number | null>(null)
  const [message, setMessage] = useState('')
  const days = useMemo(() => buildDays(visibleMonth), [visibleMonth])
  const selectedAssignments = assignments.filter((assignment) => assignment.startDate <= selectedDate && assignment.endDate >= selectedDate)
  async function save(assignment: StudentTeamAssignment) { setSavingId(assignment.id); setMessage(''); try { const response = await fetch(`/api/student/team-assignments/${assignment.id}/report`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rows: assignment.exercises.map((exercise) => ({ exerciseId: exercise.id, actualSets: exercise.actual_sets, actualWeight: exercise.actual_weight })) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || '儲存失敗。'); setMessage(result.message || '已儲存。') } catch (reason) { setMessage(reason instanceof Error ? reason.message : '儲存失敗。') } finally { setSavingId(null) } }
  function change(assignmentId: number, exerciseId: number, field: 'actual_sets' | 'actual_weight', value: string) { setAssignments((current) => current.map((assignment) => assignment.id !== assignmentId ? assignment : { ...assignment, exercises: assignment.exercises.map((exercise) => exercise.id !== exerciseId ? exercise : { ...exercise, [field]: value }) })) }
  if (!assignments.length) return <section className="lab-card mx-4 p-8 text-center text-slate-600 sm:mx-6 lg:mx-8">你目前尚未加入有進行中課表的團隊。</section>
  return <div className="space-y-6 px-4 pb-8 sm:px-6 lg:px-8" aria-live="polite">
    <section className="lab-card p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="lab-eyebrow">Team Calendar</p><h2 className="lab-section-title mt-2">{monthLabel(visibleMonth)}</h2></div><div className="flex gap-2"><button type="button" className="lab-btn-secondary !min-h-10 px-3" aria-label="上一個月" onClick={() => setVisibleMonth((value) => shiftMonth(value, -1))}>‹</button><button type="button" className="lab-btn-secondary !min-h-10 px-3" aria-label="下一個月" onClick={() => setVisibleMonth((value) => shiftMonth(value, 1))}>›</button></div></div><div className="mt-5 grid grid-cols-7 gap-1 text-center text-xs font-bold text-slate-400">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{days.map((date) => { const items = assignments.filter((assignment) => assignment.startDate <= date && assignment.endDate >= date); const active = date === selectedDate; return <button type="button" key={date} onClick={() => setSelectedDate(date)} className={`min-h-16 rounded-xl p-2 text-left transition-colors duration-150 ${active ? 'bg-sky-600 text-white' : 'bg-slate-50 text-slate-700 hover:bg-sky-50'}`} aria-label={`${date}，${items.length} 筆團隊訓練`}><span className="text-xs font-bold">{Number(date.slice(-2))}</span>{items.slice(0, 2).map((item) => <span key={item.id} className={`mt-1 block truncate rounded px-1 py-0.5 text-[10px] font-bold ${active ? 'bg-white/20' : 'bg-sky-100 text-sky-800'}`}>{item.title}</span>)}</button> })}</div></section>
    <section className="lab-card p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="lab-eyebrow">Selected Day</p><h2 className="lab-section-title mt-2">{selectedDate}</h2></div><span className="lab-badge-primary">{selectedAssignments.length} 筆課表</span></div>{message ? <p className="lab-badge-success mt-4">{message}</p> : null}<div className="mt-5 space-y-5">{selectedAssignments.length ? selectedAssignments.map((assignment) => <article key={assignment.id} className="rounded-2xl border border-slate-200 p-4 sm:p-5"><div><span className="lab-badge-info">{assignment.teamName}</span><h3 className="mt-2 text-lg font-black text-slate-900">{assignment.title}</h3><p className="mt-1 text-sm text-slate-600">{assignment.startDate} ～ {assignment.endDate}</p>{assignment.notes ? <p className="lab-copy mt-3">{assignment.notes}</p> : null}</div><div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">動作</th><th className="p-3">目標組數</th><th className="p-3">次數／時間</th><th className="p-3">建議重量</th><th className="p-3">我的組數</th><th className="p-3">我的重量</th></tr></thead><tbody>{assignment.exercises.map((exercise) => <tr key={exercise.id} className="border-b border-slate-100"><td className="p-3 font-semibold text-slate-900">{exercise.exercise_name}<div className="mt-1 text-xs font-normal text-slate-500">{exercise.section_name}</div></td><td className="p-3 text-slate-600">{exercise.sets || '-'}</td><td className="p-3 text-slate-600">{exercise.reps_or_time || '-'}</td><td className="p-3 text-slate-600">{exercise.weight || '-'}</td><td className="p-3"><input name={`actual-sets-${assignment.id}-${exercise.id}`} autoComplete="off" aria-label={`${exercise.exercise_name} 的實際組數`} className="lab-input !min-h-10 !py-2" value={exercise.actual_sets} onChange={(event) => change(assignment.id, exercise.id, 'actual_sets', event.target.value)} placeholder={exercise.sets || '組數…'} /></td><td className="p-3"><input name={`actual-weight-${assignment.id}-${exercise.id}`} autoComplete="off" aria-label={`${exercise.exercise_name} 的實際重量`} className="lab-input !min-h-10 !py-2" value={exercise.actual_weight} onChange={(event) => change(assignment.id, exercise.id, 'actual_weight', event.target.value)} placeholder={exercise.weight || '重量…'} /></td></tr>)}</tbody></table></div><button className="lab-btn-primary mt-5" disabled={savingId === assignment.id} onClick={() => void save(assignment)}>{savingId === assignment.id ? '儲存中…' : '儲存我的紀錄'}</button></article>) : <p className="rounded-2xl bg-slate-50 p-6 text-sm text-slate-600">這一天沒有團隊課表。</p>}</div></section>
  </div>
}
