'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import type { BlockRecord, CoachTeamAssignment, TeamGeneralEvent, TeamWeekMarker } from '@/services/team-training'

type Props = { teamId: number; initialAssignments: CoachTeamAssignment[]; initialWeekMarkers: TeamWeekMarker[]; initialEvents: TeamGeneralEvent[]; blocks: BlockRecord[] }
type Day = { date: string; day: number; current: boolean; assignments: CoachTeamAssignment[]; events: TeamGeneralEvent[]; markers: TeamWeekMarker[] }
const WEEKDAYS = ['一', '二', '三', '四', '五', '六', '日']
const COLORS = ['sky', 'emerald', 'amber', 'violet', 'rose', 'slate'] as const

function today() { return new Date().toISOString().slice(0, 10) }
function shiftMonth(value: string, offset: number) { const [year, month] = value.split('-').map(Number); const date = new Date(year, month - 1 + offset, 1); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}` }
function monthLabel(value: string) { const [year, month] = value.split('-'); return `${year}年 ${Number(month)}月` }
function buildDays(month: string, assignments: CoachTeamAssignment[], events: TeamGeneralEvent[], markers: TeamWeekMarker[]): Day[] { const first = new Date(`${month}-01T00:00:00`); const firstOffset = (first.getDay() + 6) % 7; const total = new Date(first.getFullYear(), first.getMonth() + 1, 0).getDate(); return Array.from({ length: Math.ceil((firstOffset + total) / 7) * 7 }, (_, index) => { const date = new Date(first.getFullYear(), first.getMonth(), index - firstOffset + 1); const iso = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; return { date: iso, day: date.getDate(), current: date.getMonth() === first.getMonth(), assignments: assignments.filter((item) => item.startDate <= iso && item.endDate >= iso), events: events.filter((item) => item.startDate <= iso && item.endDate >= iso), markers: markers.filter((item) => item.startDate <= iso && item.endDate >= iso) } }) }

export function CoachTeamCalendar({ teamId, initialAssignments, initialWeekMarkers, initialEvents, blocks }: Props) {
  const router = useRouter()
  const [selectedDate, setSelectedDate] = useState(today())
  const [visibleMonth, setVisibleMonth] = useState(today().slice(0, 7))
  const [saving, setSaving] = useState(false)
  const [notice, setNotice] = useState('')
  const [weekColor, setWeekColor] = useState<(typeof COLORS)[number]>('sky')
  const days = useMemo(() => buildDays(visibleMonth, initialAssignments, initialEvents, initialWeekMarkers), [visibleMonth, initialAssignments, initialEvents, initialWeekMarkers])
  const dayAssignments = initialAssignments.filter((item) => item.startDate <= selectedDate && item.endDate >= selectedDate)
  const dayEvents = initialEvents.filter((item) => item.startDate <= selectedDate && item.endDate >= selectedDate)

  async function request(path: string, body: unknown) { const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || '儲存失敗。'); return data }
  async function save(form: FormData, kind: 'week' | 'assignment' | 'event') { setSaving(true); setNotice(''); try { const path = kind === 'week' ? `/api/coach/teams/${teamId}/week-markers` : kind === 'event' ? `/api/coach/teams/${teamId}/events` : `/api/coach/teams/${teamId}/assignments`; const body = kind === 'week' ? { startDate: form.get('startDate'), endDate: form.get('endDate'), weekNum: Number(form.get('weekNum')), note: form.get('weekNote'), colorKey: weekColor } : kind === 'event' ? { title: form.get('eventTitle'), eventType: form.get('eventType'), startDate: selectedDate, endDate: form.get('eventEndDate') || selectedDate, notes: form.get('eventNotes') } : { blockId: Number(form.get('blockId')), title: form.get('title'), startDate: selectedDate, endDate: form.get('endDate') || selectedDate, notes: form.get('notes') }; const result = await request(path, body); setNotice(result.message || '已儲存。'); router.refresh() } catch (error) { setNotice(error instanceof Error ? error.message : '儲存失敗。') } finally { setSaving(false) } }

  return <div className="space-y-6 px-4 pb-8 sm:px-6 lg:px-8"><article className="lab-card overflow-hidden"><header className="bg-[#171717] px-7 py-8 text-white sm:px-9"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.2em] text-slate-300">CALENDAR PLANNER</p><h2 className="mt-3 text-4xl font-black tracking-tight">課表行事曆</h2></div><span className="rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-800">已選日期：{selectedDate}</span></div></header><div className="p-7 sm:p-9"><p className="lab-copy">先用月曆挑一天，再安排團隊課表或新增一般事件。所有活躍成員會在自己的行事曆中同步看到。</p>
      <section className="mt-7 rounded-[1.5rem] border border-slate-200 bg-white p-5 sm:p-7"><h3 className="text-lg font-bold text-slate-900">行事曆週期標示</h3><p className="mt-2 text-sm text-slate-500">先設定日期區間，再標示這段時間屬於哪個 Week。</p><form className="mt-5 grid gap-4 lg:grid-cols-[1fr_1fr_150px_1fr_auto]" onSubmit={(event) => { event.preventDefault(); void save(new FormData(event.currentTarget), 'week') }}><label className="grid gap-1 text-sm font-semibold">開始日期<input name="startDate" type="date" defaultValue={selectedDate} className="lab-input" /></label><label className="grid gap-1 text-sm font-semibold">結束日期<input name="endDate" type="date" defaultValue={selectedDate} className="lab-input" /></label><label className="grid gap-1 text-sm font-semibold">Week<input name="weekNum" type="number" min="1" defaultValue="1" className="lab-input" /></label><label className="grid gap-1 text-sm font-semibold">備註<input name="weekNote" autoComplete="off" className="lab-input" placeholder="例如：第一週、恢復週…" /></label><button className="lab-btn-primary self-end" disabled={saving}>{saving ? '儲存中…' : '套用週期'}</button></form><div className="mt-4 flex flex-wrap gap-2">{COLORS.map((color) => <button type="button" key={color} onClick={() => setWeekColor(color)} className={`rounded-full border px-4 py-2 text-sm font-bold ${weekColor === color ? 'border-sky-700 bg-sky-100 text-sky-800' : 'border-slate-200 bg-white text-slate-600'}`}>{({ sky: '藍色', emerald: '綠色', amber: '橘色', violet: '紫色', rose: '粉色', slate: '灰色' })[color]}</button>)}</div><div className="mt-4 flex flex-wrap gap-2">{initialWeekMarkers.map((marker) => <span key={marker.id} className="lab-badge bg-slate-100 text-slate-700">Week {marker.weekNum}｜{marker.startDate} ～ {marker.endDate}{marker.note ? `｜${marker.note}` : ''}</span>)}</div></section>
      <section className="mt-7 rounded-[1.5rem] border border-slate-200 bg-slate-50/80 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><button type="button" className="lab-btn-secondary" onClick={() => setVisibleMonth((value) => shiftMonth(value, -1))}>上個月</button><div className="text-center"><h3 className="text-xl font-bold text-slate-900">{monthLabel(visibleMonth)}</h3><p className="mt-1 text-xs text-slate-500">點一天即可預覽下方的課表安排與一般事件表單</p></div><button type="button" className="lab-btn-secondary" onClick={() => setVisibleMonth((value) => shiftMonth(value, 1))}>下個月</button></div><div className="mt-5 overflow-x-auto"><div className="min-w-[760px]"><div className="grid gap-px rounded-t-[1.25rem] bg-slate-200" style={{ gridTemplateColumns: 'repeat(7, minmax(0, 1fr))' }}>{WEEKDAYS.map((day, index) => <div key={day} className={`bg-white px-3 py-3 text-center text-xs font-semibold tracking-[0.16em] ${index >= 5 ? 'text-orange-500' : 'text-slate-500'}`}>{day}</div>)}</div><div className="grid gap-px rounded-b-[1.25rem] bg-slate-200" style={{ gridTemplateColumns: 'repeat(7, minmax(0, 1fr))' }}>{days.map((day) => <button type="button" key={day.date} onClick={() => setSelectedDate(day.date)} className={`relative flex min-h-[132px] flex-col bg-white p-3 text-left transition hover:z-10 hover:bg-slate-50 focus-visible:z-20 focus-visible:ring-2 focus-visible:ring-sky-400 ${day.date === selectedDate ? 'z-10 bg-sky-50 ring-2 ring-inset ring-sky-400' : ''} ${day.current ? 'text-slate-900' : 'text-slate-300'}`}><span className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold ${day.date === selectedDate ? 'bg-sky-500 text-white' : day.date === today() ? 'bg-slate-900 text-white' : 'bg-slate-100'}`}>{day.day}</span><div className="mt-3 space-y-2">{day.assignments.slice(0, 2).map((item) => <span key={item.id} className="block truncate rounded-xl bg-orange-100 px-2.5 py-1.5 text-[11px] font-medium text-orange-700">{item.title}</span>)}{day.events.slice(0, 2).map((item) => <span key={item.id} className="block truncate rounded-xl bg-emerald-100 px-2.5 py-1.5 text-[11px] font-medium text-emerald-700">{item.title}</span>)}</div></button>)}</div></div></div></section>
      <section className="mt-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="lab-eyebrow">Selected Day</p><h3 className="lab-section-title mt-2">{selectedDate}</h3></div><div className="flex gap-2"><span className="lab-badge bg-slate-100 text-slate-700">課表 {dayAssignments.length}</span><span className="lab-badge bg-slate-100 text-slate-700">事件 {dayEvents.length}</span></div></div><div className="mt-5 space-y-3">{dayAssignments.map((item) => <div key={item.id} className="rounded-[1.25rem] border border-orange-200 bg-white p-5"><b>{item.title}</b><p className="mt-2 text-sm text-slate-600">{item.startDate} ～ {item.endDate}</p></div>)}{dayEvents.map((item) => <div key={item.id} className="rounded-[1.25rem] border border-emerald-200 bg-white p-5"><b>{item.title}</b><p className="mt-2 text-sm text-slate-600">{item.eventType}｜{item.startDate} ～ {item.endDate}</p></div>)}{!dayAssignments.length && !dayEvents.length ? <div className="lab-card-muted p-5 text-sm text-slate-600">這一天目前沒有任何安排。</div> : null}</div></section>
      <section className="mt-7 grid gap-6 xl:grid-cols-2"><form className="rounded-[1.5rem] border border-slate-200 bg-white p-5" onSubmit={(event) => { event.preventDefault(); void save(new FormData(event.currentTarget), 'assignment') }}><p className="lab-eyebrow">Add Assignment</p><h3 className="mt-2 text-xl font-bold text-slate-900">安排團隊課表</h3><label className="mt-4 grid gap-1 text-sm font-semibold">訓練板塊<select name="blockId" required className="lab-input"><option value="">請選擇…</option>{blocks.map((block) => <option key={block.id} value={block.id}>{block.block_code || ''} {block.block_name || `板塊 #${block.id}`}</option>)}</select></label><label className="mt-3 grid gap-1 text-sm font-semibold">顯示名稱<input name="title" autoComplete="off" className="lab-input" placeholder="例如：Week 1 下肢力量…" /></label><label className="mt-3 grid gap-1 text-sm font-semibold">結束日期<input name="endDate" type="date" defaultValue={selectedDate} className="lab-input" /></label><label className="mt-3 grid gap-1 text-sm font-semibold">教練備註<textarea name="notes" autoComplete="off" className="lab-input min-h-20" placeholder="全隊共用提醒…" /></label><button className="lab-btn-primary mt-5" disabled={saving}>{saving ? '儲存中…' : '建立課表安排'}</button></form><form className="rounded-[1.5rem] border border-slate-200 bg-white p-5" onSubmit={(event) => { event.preventDefault(); void save(new FormData(event.currentTarget), 'event') }}><p className="lab-eyebrow">Add Event</p><h3 className="mt-2 text-xl font-bold text-slate-900">新增一般事件</h3><label className="mt-4 grid gap-1 text-sm font-semibold">事件名稱<input name="eventTitle" autoComplete="off" className="lab-input" placeholder="例如：比賽、集訓…" /></label><label className="mt-3 grid gap-1 text-sm font-semibold">事件類型<select name="eventType" className="lab-input"><option>比賽</option><option>檢測</option><option>集訓</option><option>提醒</option><option>其他</option></select></label><label className="mt-3 grid gap-1 text-sm font-semibold">結束日期<input name="eventEndDate" type="date" defaultValue={selectedDate} className="lab-input" /></label><label className="mt-3 grid gap-1 text-sm font-semibold">備註<textarea name="eventNotes" autoComplete="off" className="lab-input min-h-20" placeholder="團隊事件說明…" /></label><button className="lab-btn-secondary mt-5" disabled={saving}>{saving ? '儲存中…' : '新增一般事件'}</button></form></section>{notice ? <p className="mt-5 text-sm font-semibold text-emerald-700" aria-live="polite">{notice}</p> : null}</div></article><Link className="lab-btn-secondary" href="/coach/teams">返回團隊列表</Link></div>
}
